---
title: "1_scoringSL_followup"
output: html_notebook
---

```{r}
library(tidyverse)
source("reverseCode.R")
```

#still need code for AES-M

#read in data
```{r}
ogsurveyresponses <- read.csv(file='../data/SL_followup/survey_responsesOGrun.csv') #score PAS, BMRQ, and goldMSI
MET <- read.csv(file='../data/SL_followup/data_exp_106990-v4_task-sv8h.csv') #clean & score MET
followup <- read.csv(file='../data/SL_followup/Groove)_March 22, 2023_07.53.csv') #score everything
```

#MET cleaning/scoring
```{r}
#double check this is accurate
MET_cleaned <- MET %>%
  dplyr::select(Participant.Public.ID, Response, Correct, display) %>%
  subset(Response != "AUDIO PLAY REQUESTED") %>%
  subset(Response != "") %>%
  subset(display !="Practice") %>%
  subset(display !="practice_ritmo")

melodic_score <- MET_cleaned %>%
  subset(display == "Melodia") %>%
  group_by(Participant.Public.ID) %>%
  summarise_at(vars(Correct), list(name = sum))

names(melodic_score)[2] <- "MET_melodicscore"

rhythmic_score <- MET_cleaned %>%
  subset(display == "Ritmo") %>%
  group_by(Participant.Public.ID) %>%
  summarise_at(vars(Correct), list(name = sum))
names(rhythmic_score)[2] <- "MET_rhythmicscore"

MET_scores <- merge(melodic_score, rhythmic_score)
```

#BMRQ
```{r}
bmrq <- ogsurveyresponses %>%
  dplyr::select("Please.choose.the.most.appropriate.category....When.I.share.music.with.someone.I.feel.a.special.connection.with.that.person.":"Please.choose.the.most.appropriate.category....When.I.hear.a.tune.I.like.a.lot.I.can.t.help.tapping.or.moving.to.its.beat.")

bmrq$X21..Mark..Completely.Agree..for.this.question....Completely.Disagree.Completely.Agree <- NULL

# BMRQ columns to reverse code and sub-score
cols_reverse <- c("Please.choose.the.most.appropriate.category....In.my.free.time.I.hardly.listen.to.music.",
                  "Please.choose.the.most.appropriate.category....I.don.t.like.to.dance..not.even.with.music.I.like.")

cols_emotion <- c("Please.choose.the.most.appropriate.category....I.like.listen.to.music.that.contains.emotion.",
  "Please.choose.the.most.appropriate.category....I.get.emotional.listening.to.certain.pieces.of.music.",
  "Please.choose.the.most.appropriate.category....I.can.become.tearful.or.cry.when.I.listen.to.a.melody.that.I.like.very.much.",
  "Please.choose.the.most.appropriate.category....I.sometimes.feel.chills.when.I.hear.a.melody.that.I.like.")

cols_sensorimotor <-c("Please.choose.the.most.appropriate.category....I.don.t.like.to.dance..not.even.with.music.I.like.",
  "Please.choose.the.most.appropriate.category....Music.often.makes.me.dance.",
  "Please.choose.the.most.appropriate.category....I.can.t.help.humming.or.singing.along.to.music.that.I.like.",
  "Please.choose.the.most.appropriate.category....When.I.hear.a.tune.I.like.a.lot.I.can.t.help.tapping.or.moving.to.its.beat.")
                      
cols_moodreg <- c("Please.choose.the.most.appropriate.category....Music.keeps.me.company.when.I.m.alone.",
  "Please.choose.the.most.appropriate.category....Music.calms.and.relaxes.me.",
  "Please.choose.the.most.appropriate.category....Music.helps.me.chill.out.",
  "Please.choose.the.most.appropriate.category....Music.comforts.me.")

cols_musicseek <- c("Please.choose.the.most.appropriate.category....In.my.free.time.I.hardly.listen.to.music.",
  "Please.choose.the.most.appropriate.category....I.inform.myself.about.music.I.like.",
  "Please.choose.the.most.appropriate.category....I.m.always.looking.for.new.music.",
  "Please.choose.the.most.appropriate.category....I.spend.quite.a.bit.of.money.on.music.and.related.items.")

cols_socialreward <-c("Please.choose.the.most.appropriate.category....When.I.share.music.with.someone.I.feel.a.special.connection.with.that.person.",
  "Please.choose.the.most.appropriate.category....Music.makes.me.bond.with.other.people.",
  "Please.choose.the.most.appropriate.category....I.like.to.sing.or.play.an.instrument.with.other.people.",
                     "Please.choose.the.most.appropriate.category....At.a.concert.I.feel.connected.to.the.performers.and.the.audience.")

# Reverse code
bmrq[cols_reverse] <- lapply(bmrq[cols_reverse], reverseCode)


# Add sub-scores and total to main df
ogsurveyresponses$BMRQ_total <- apply(bmrq,1, sum) # total BMRQ scores
ogsurveyresponses$BMRQ_emotion <- apply(bmrq[cols_emotion], 1,sum)
ogsurveyresponses$BMRQ_sensorimotor <- apply(bmrq[cols_sensorimotor],1, sum)
ogsurveyresponses$BMRQ_moodreg <-apply(bmrq[cols_moodreg],1, sum)
ogsurveyresponses$BMRQ_musicseek <- apply(bmrq[cols_musicseek],1, sum)
ogsurveyresponses$BMRQ_socialreward <- apply(bmrq[cols_socialreward],1, sum)
```


#goldMSI
```{r}
Gold <- ogsurveyresponses %>%
  dplyr::select("Please.choose.the.most.appropriate.category....I.spend.a.lot.of.free.time.doing.music.related.activities.":"Per.day..I.listen.attentively.to.music.for.")

#delete atttention checking question

# GoldMSI columns to reverse code and sub-score (for these questions, the correct answer (ie the more positive answer) is a higher number. Negative questions are reverse coded.) 

cols_reverse <- c("Please.choose.the.most.appropriate.category....I.don.t.spend.much.of.my.disposable.income.on.music." , 
"Please.choose.the.most.appropriate.category....I.find.it.difficult.to.spot.mistakes.in.a.performance.of.a.song.even.if.I.know.the.tune." , 
"Please.choose.the.most.appropriate.category....I.have.trouble.recognizing.a.familiar.song.when.played.in.a.different.way.or.by.a.different.performer." , 
"Please.choose.the.most.appropriate.category....When.I.sing..I.have.no.idea.whether.I.m.in.tune.or.not." , 
"Please.choose.the.most.appropriate.category....I.have.never.been.complimented.for.my.talents.as.a.musical.performer." , 
"Please.choose.the.most.appropriate.category....I.would.not.consider.myself.a.musician." , 
"Please.choose.the.most.appropriate.category....I.am.not.able.to.sing.in.harmony.when.somebody.is.singing.a.familiar.tune." , 
"Please.choose.the.most.appropriate.category....I.don.t.like.singing.in.public.because.I.m.afraid.that.I.would.sing.wrong.notes." , 
"Please.choose.the.most.appropriate.category....Pieces.of.music.rarely.evoke.emotions.for.me.")

cols_activeengagement <- c("Please.choose.the.most.appropriate.category....I.spend.a.lot.of.free.time.doing.music.related.activities." , 
"Please.choose.the.most.appropriate.category....I.enjoy.writing.about.music..for.example.on.blogs.and.forums." , 
"Please.choose.the.most.appropriate.category....I.m.intrigued.by.musical.styles.I.m.not.familiar.with.and.want.to.find.out.more." , 
"Please.choose.the.most.appropriate.category....I.often.read.or.search.the.internet.for.things.related.to.music." , 
"Please.choose.the.most.appropriate.category....I.don.t.spend.much.of.my.disposable.income.on.music." , 
"Please.choose.the.most.appropriate.category....Music.is.kind.of.an.addiction.for.me..I.couldn.t.live.without.it." , 
"Please.choose.the.most.appropriate.category....I.keep.track.of.new.music.that.I.come.across..e.g.new.artists.or.recordings.." , 
"I.have.attended.this.many.live.music.events.as.an.audience.member.in.the.past.twelve.months." , 
"Per.day..I.listen.attentively.to.music.for.")

cols_perceptualabilities <- c("Please.choose.the.most.appropriate.category....I.am.able.to.judge.whether.someone.is.a.good.singer.or.not." , 
"Please.choose.the.most.appropriate.category....I.usually.know.when.I.m.hearing.a.song.for.the.first.time." , "Please.choose.the.most.appropriate.category....I.find.it.difficult.to.spot.mistakes.in.a.performance.of.a.song.even.if.I.know.the.tune." , 
"Please.choose.the.most.appropriate.category....I.can.compare.and.discuss.differences.between.two.performances.or.versions.of.the.same.piece.of.music." , 
"Please.choose.the.most.appropriate.category....I.have.trouble.recognizing.a.familiar.song.when.played.in.a.different.way.or.by.a.different.performer." , 
"Please.choose.the.most.appropriate.category....I.can.tell.when.people.sing.or.play.out.of.time.with.the.beat." , 
"Please.choose.the.most.appropriate.category....I.can.tell.when.people.sing.or.play.out.of.tune." , 
"Please.choose.the.most.appropriate.category....When.I.sing..I.have.no.idea.whether.I.m.in.tune.or.not." , 
"Please.choose.the.most.appropriate.category....When.I.hear.a.piece.of.music.I.can.usually.identify.its.genre.")

cols_musicaltraining <- c("Please.choose.the.most.appropriate.category....I.have.never.been.complimented.for.my.talents.as.a.musical.performer." , "Please.choose.the.most.appropriate.category....I.would.not.consider.myself.a.musician.", 
"I.engaged.in.regular..daily.practice.of.a.musical.instrument..including.voice..for." , 
"On.average..at.the.peak.of.my.interest..I.practiced.my.primary.instrument.this.many.hours.per.day....Selected.Choice" , 
"I.have.had.formal.training.in.music.theory.for." , 
"During.my.lifetime..I.have.had.formal.training.on.a.music.instrument..including.voice..for." , 
"I.can.play.this.many.musical.instruments.")



cols_singingabilities <- c("Please.choose.the.most.appropriate.category....If.somebody.starts.singing.a.song.I.don.t.know..I.can.usually.join.in." , 
"Please.choose.the.most.appropriate.category....I.can.sing.or.play.music.from.memory." , 
"Please.choose.the.most.appropriate.category....I.am.able.to.hit.the.right.notes.when.I.sing.along.with.a.recording." , 
"Please.choose.the.most.appropriate.category....I.am.not.able.to.sing.in.harmony.when.somebody.is.singing.a.familiar.tune." , 
"Please.choose.the.most.appropriate.category....I.don.t.like.singing.in.public.because.I.m.afraid.that.I.would.sing.wrong.notes." , 
"Please.choose.the.most.appropriate.category....After.hearing.a.new.song.two.or.three.times..I.can.usually.sing.it.by.myself." , 
"Please.choose.the.most.appropriate.category....I.only.need.to.hear.a.new.tune.once.and.I.can.sing.it.back.hours.later.")


cols_emotion <- c("Please.choose.the.most.appropriate.category....I.sometimes.choose.music.that.can.trigger.shivers.down.my.spine." , 
"Please.choose.the.most.appropriate.category....Pieces.of.music.rarely.evoke.emotions.for.me." , 
"Please.choose.the.most.appropriate.category....I.often.pick.certain.music.to.motivate.or.excite.me." , 
"Please.choose.the.most.appropriate.category....I.am.able.to.identify.what.is.special.about.a.given.musical.piece." , 
"Please.choose.the.most.appropriate.category....I.am.able.to.talk.about.the.emotions.that.a.piece.of.music.evokes.for.me." , 
"Please.choose.the.most.appropriate.category....Music.can.evoke.my.memories.of.past.people.and.places.")

cols_musicalsophistication <- c("Please.choose.the.most.appropriate.category....I.spend.a.lot.of.free.time.doing.music.related.activities." , 
           "Please.choose.the.most.appropriate.category....I.enjoy.writing.about.music..for.example.on.blogs.and.forums." , 
"Please.choose.the.most.appropriate.category....If.somebody.starts.singing.a.song.I.don.t.know..I.can.usually.join.in." , 
"Please.choose.the.most.appropriate.category....I.can.sing.or.play.music.from.memory." , 
"Please.choose.the.most.appropriate.category....I.am.able.to.hit.the.right.notes.when.I.sing.along.with.a.recording." , 
"Please.choose.the.most.appropriate.category....I.can.compare.and.discuss.differences.between.two.performances.or.versions.of.the.same.piece.of.music." , 
"Please.choose.the.most.appropriate.category....I.have.never.been.complimented.for.my.talents.as.a.musical.performer." , 
"Please.choose.the.most.appropriate.category....I.often.read.or.search.the.internet.for.things.related.to.music." , 
"Please.choose.the.most.appropriate.category....I.am.not.able.to.sing.in.harmony.when.somebody.is.singing.a.familiar.tune." , 
"Please.choose.the.most.appropriate.category....I.am.able.to.identify.what.is.special.about.a.given.musical.piece." , 
"Please.choose.the.most.appropriate.category....When.I.sing..I.have.no.idea.whether.I.m.in.tune.or.not." , 
"Please.choose.the.most.appropriate.category....Music.is.kind.of.an.addiction.for.me..I.couldn.t.live.without.it." , 
"Please.choose.the.most.appropriate.category....I.don.t.like.singing.in.public.because.I.m.afraid.that.I.would.sing.wrong.notes." , 
"Please.choose.the.most.appropriate.category....I.would.not.consider.myself.a.musician." , 
"Please.choose.the.most.appropriate.category....After.hearing.a.new.song.two.or.three.times..I.can.usually.sing.it.by.myself." , 
"I.engaged.in.regular..daily.practice.of.a.musical.instrument..including.voice..for." , 
"On.average..at.the.peak.of.my.interest..I.practiced.my.primary.instrument.this.many.hours.per.day....Selected.Choice" , "I.can.play.this.many.musical.instruments.")

# Reverse code

Gold[cols_reverse] <- lapply(Gold[cols_reverse], reverseCode, min=1, max=7)

# Add sub-scores and total to main df
#ogsurveyresponses$Gold_total <- apply(Gold,1, sum)/38 # total GoldMSI score
ogsurveyresponses$Gold_activeengagement <- apply(Gold[cols_activeengagement], 1,sum)/9
ogsurveyresponses$Gold_perceptualabilities <- apply(Gold[cols_perceptualabilities],1, sum)/9
ogsurveyresponses$Gold_musicaltraining <-apply(Gold[cols_musicaltraining],1, sum)/7
ogsurveyresponses$Gold_singingabilities <- apply(Gold[cols_singingabilities],1, sum)/7
ogsurveyresponses$Gold_singingabilities <- apply(Gold[cols_singingabilities],1, sum)/7
ogsurveyresponses$Gold_emotion <- apply(Gold[cols_emotion],1, sum)/6
ogsurveyresponses$Gold_musicalsophistication <- apply(Gold[cols_musicalsophistication],1, sum)/18
```

#PAS Scoring
```{r}
#PAS Scoring
PASS <- ogsurveyresponses %>%
  dplyr::select("I.have.usually.found.lovemaking.to.be.intensely.pleasurable.":"I.have.been.fascinated.with.the.dancing.of.flames.in.a.fireplace.")

#delete column CJ which is an attention-checking question
PASS$Mark..False..for.this.question. <- NULL

# Replace 1s with 0s --> CURRENTLY REGULARLY CODED
PASS[PASS == 1] <- 1
# Replace 2s with 1s
PASS[PASS == 2] <- 0


# PAS columns to reverse code and sub-score (for these questions, the correct answer (ie the more anhedonic answer) is false.)

cols_reverse <- c("I.have.usually.found.lovemaking.to.be.intensely.pleasurable.",
"When.eating.a.favorite.food..I.have.often.tried.to.eat.slowly.to.make.it.last.longer." ,
"I.have.often.enjoyed.the.feel.of.silk..velvet..or.fur." ,
"I.have.sometimes.enjoyed.feeling.the.strength.in.my.muscles." ,
"The.taste.of.food.has.always.been.important.to.me." ,
"I.have.always.loved.having.my.back.massaged." ,
"Trying.new.foods.is.something.I.have.always.enjoyed." ,
"When.I.have.seen.a.statue..I.have.had.the.urge.to.feel.it." ,
"I.have.always.had.a.number.of.favorite.foods." ,
"When.I.have.walked.by.a.bakery..the.smell.of.fresh.bread.has.often.made.me.hungry." ,
"I.have.often.enjoyed.receiving.a.strong..warm.handshake." ,
"Standing.on.a.high.place.and.looking.out.over.the.view.is.very.exciting." , 
"I.have.often.found.walks.to.be.relaxing.and.enjoyable." , "The.sound.of.the.rain.falling.on.the.roof.has.made.me.feel.snug.and.secure." ,
"I.like.playing.with.and.petting.soft.little.kittens.or.puppies." , "The.sound.of.organ.music.has.often.thrilled.me." ,
"Beautiful.scenery.has.been.a.great.delight.to.me." ,
"The.first.winter.snowfall.has.often.looked.pretty.to.me." , "I.have.sometimes.danced.by.myself.just.to.feel.my.body.move.with.the.music." ,
"On.seeing.a.soft..thick.carpet..I.have.sometimes.had.the.impulse.to.take.off.my.shoes.and.walk.barefoot.on.it." ,
"After.a.busy.day..a.slow.walk.has.often.felt.relaxing." , "The.bright.lights.of.a.city.are.exciting.to.look.at." ,
"It.has.always.made.me.feel.good.when.someone.I.care.about.reaches.out.to.touch.me." ,
"When.I.pass.by.flowers..I.have.often.stopped.to.smell.them." ,
"Sex.is.the.most.intensely.enjoyable.thing.in.life." ,
"It.has.often.felt.good.to.massage.my.muscles.when.they.are.tired.or.sore." ,
"When.I.m.feeling.a.little.sad..singing.has.often.made.me.feel.happier." , "A.good.soap.lather.when.I.m.bathing.has.sometimes.soothed.and.refreshed.me." ,
"A.brisk.walk.has.sometimes.made.me.feel.good.all.over." , "I.have.been.fascinated.with.the.dancing.of.flames.in.a.fireplace.")
          

cols_sex <- c("I.have.usually.found.lovemaking.to.be.intensely.pleasurable." , 
"I.have.seldom.enjoyed.any.kind.of.sexual.experience." , 
"Sex.is.okay..but.not.as.much.fun.as.most.people.claim.it.is." , 
"Sex.is.the.most.intensely.enjoyable.thing.in.life.")

cols_eating <-c("When.eating.a.favorite.food..I.have.often.tried.to.eat.slowly.to.make.it.last.longer." ,     "The.taste.of.food.has.always.been.important.to.me." , 
"Trying.new.foods.is.something.I.have.always.enjoyed." , 
"I.have.always.had.a.number.of.favorite.foods." , 
"I.have.had.very.little.desire.to.try.new.kinds.of.foods." , 
"I.ve.never.cared.much.about.the.texture.of.food." , 
"One.food.tastes.as.good.as.another.to.me." , "The.smell.of.dinner.cooking.has.hardly.ever.aroused.my.appetite.")
                      
cols_touch <- c("I.have.often.enjoyed.the.feel.of.silk..velvet..or.fur." , 
"I.have.always.loved.having.my.back.massaged." , 
"When.I.have.seen.a.statue..I.have.had.the.urge.to.feel.it." , 
"I.never.have.the.desire.to.take.off.my.shoes.and.walk.through.a.puddle.barefoot." , 
"I.have.often.enjoyed.receiving.a.strong..warm.handshake." , 
"I.have.often.felt.uncomfortable.when.my.friends.touch.me." , 
"I.like.playing.with.and.petting.soft.little.kittens.or.puppies." , "On.seeing.a.soft..thick.carpet..I.have.sometimes.had.the.impulse.to.take.off.my.shoes.and.walk.barefoot.on.it." , 
"It.has.always.made.me.feel.good.when.someone.I.care.about.reaches.out.to.touch.me." , 
"It.has.often.felt.good.to.massage.my.muscles.when.they.are.tired.or.sore." ,
"A.good.soap.lather.when.I.m.bathing.has.sometimes.soothed.and.refreshed.me.")

cols_feeling <- c("I.have.sometimes.enjoyed.feeling.the.strength.in.my.muscles.")

cols_sound <- c("I.have.always.found.organ.music.dull.and.unexciting.",
"On.hearing.a.good.song..I.have.seldom.wanted.to.sing.along.with.it.", 
"The.sound.of.rustling.leaves.has.never.much.pleased.me.", 
"I.don.t.know.why.some.people.are.so.interested.in.music.", 
"I.have.never.found.a.thunderstorm.exhilarating.", 
"The.sound.of.the.rain.falling.on.the.roof.has.made.me.feel.snug.and.secure." ,
"The.sound.of.organ.music.has.often.thrilled.me.", 
"I.have.seldom.cared.to.sing.in.the.shower.", 
"I.have.usually.found.soft.music.boring.rather.than.relaxing.", "The.sounds.of.a.parade.have.never.excited.me." , 
"When.I.m.feeling.a.little.sad..singing.has.often.made.me.feel.happier.")

cols_vision <- c("The.color.that.things.are.painted.has.seldom.mattered.to.me." ,
"I.don.t.understand.why.people.enjoy.looking.at.the.stars.at.night.",
"Flowers.are.not.as.beautiful.as.many.people.claim." , 
"Poets.always.exaggerate.the.beauty.and.joys.of.nature." , 
"Standing.on.a.high.place.and.looking.out.over.the.view.is.very.exciting." , 
"Beautiful.scenery.has.been.a.great.delight.to.me." , 
"The.first.winter.snowfall.has.often.looked.pretty.to.me." , 
"The.bright.lights.of.a.city.are.exciting.to.look.at." , 
"The.beauty.of.sunsets.is.greatly.overrated." , 
"I.have.been.fascinated.with.the.dancing.of.flames.in.a.fireplace.")

cols_movement <-c ("Dancing..or.the.idea.of.it..has.always.seemed.dull.to.me.",
"I.have.had.very.little.fun.from.physical.activities.like.walking..swimming..or.sports." , 
"I.have.always.hated.the.feeling.of.exhaustion.that.comes.from.vigorous.activity." , 
"I.never.wanted.to.go.on.any.of.the.rides.at.an.amusement.park." , 
"I.have.often.found.walks.to.be.relaxing.and.enjoyable." , 
"I.have.sometimes.danced.by.myself.just.to.feel.my.body.move.with.the.music." , 
"After.a.busy.day..a.slow.walk.has.often.felt.relaxing." , 
"I.think.that.flying.a.kite.is.silly." , 
"A.brisk.walk.has.sometimes.made.me.feel.good.all.over.")

cols_temperature <-c ("Sunbathing.isn.t.really.more.fun.than.lying.down.indoors." , "The.warmth.of.an.open.fireplace.hasn.t.especially.soothed.and.calmed.me." , "I.ve.never.cared.to.sunbathe..it.just.makes.me.hot.")

cols_general <-c("There.just.are.not.many.things.that.I.have.ever.really.enjoyed.doing.")

cols_smell <- c ("When.I.have.walked.by.a.bakery..the.smell.of.fresh.bread.has.often.made.me.hungry." , 
"When.I.pass.by.flowers..I.have.often.stopped.to.smell.them.")

# this question was not categorized I.have.usually.finished.my.bath.or.shower.as.quickly.as.possible.just.to.get.it.over.with.

# Reverse code

PASS[cols_reverse] <- lapply(PASS[cols_reverse], reverseCode, min=0, max=1)

# Add sub-scores and total to main df
ogsurveyresponses$PASS_total <- apply(PASS,1, sum) # total PAS scores
ogsurveyresponses$PASS_sex <- apply(PASS[cols_sex], 1,sum)
ogsurveyresponses$PASS_eating <- apply(PASS[cols_eating],1, sum)
ogsurveyresponses$PASS_touch <-apply(PASS[cols_touch],1, sum)
ogsurveyresponses$PASS_feeling <- apply(PASS[cols_feeling],1, sum)
ogsurveyresponses$PASS_sound <- apply(PASS[cols_sound],1, sum)
ogsurveyresponses$PASS_vision <- apply(PASS[cols_vision],1, sum)
ogsurveyresponses$PASS_movement <- apply(PASS[cols_movement],1, sum)
ogsurveyresponses$PASS_temperature <- apply(PASS[cols_temperature],1, sum)
ogsurveyresponses$PASS_general <- apply(PASS[cols_general],1, sum)
ogsurveyresponses$PASS_smell <- apply(PASS[cols_smell],1, sum)
```

# QUIC (childhood + adolescence)
```{r}
### CHILDHOOD ###
#QUIC Scoring
QUIC_child <- followup %>%
  dplyr::select("QUIC_child1":"QUIC_child38")

#recode verbal responses (if not numbers)
QUIC_child[QUIC_child == "Yes"] <- as.numeric(1)
QUIC_child[QUIC_child == "No"] <- as.numeric(0)
QUIC_child[1:38] <- as.numeric(unlist(QUIC_child[1:38]))

cols_reverse <- c("QUIC_child1", "QUIC_child3", "QUIC_child4", "QUIC_child5", "QUIC_child6", "QUIC_child7", "QUIC_child8",
                  "QUIC_child9", "QUIC_child10", "QUIC_child14", "QUIC_child15", "QUIC_child17", "QUIC_child28", "QUIC_child36")

cols_parentalmonitoring <- c("QUIC_child1", "QUIC_child3", "QUIC_child4", "QUIC_child5", "QUIC_child6", "QUIC_child7",
                  "QUIC_child9", "QUIC_child10", "QUIC_child14")

cols_parentalpredictability <- c("QUIC_child2", "QUIC_child8","QUIC_child11", "QUIC_child12", "QUIC_child15","QUIC_child16", "QUIC_child17","QUIC_child31","QUIC_child32","QUIC_child33", "QUIC_child34","QUIC_child35")

cols_parentalenvironment <- c("QUIC_child18", "QUIC_child19","QUIC_child21", "QUIC_child22", "QUIC_child28","QUIC_child29", "QUIC_child30")

cols_physiscalenvironment <- c("QUIC_child13", "QUIC_child20",  "QUIC_child26", "QUIC_child27", "QUIC_child36", "QUIC_child37", "QUIC_child38")

cols_safetyandsecurity <- c("QUIC_child23", "QUIC_child24", "QUIC_child25")

# Reverse code
QUIC_child[cols_reverse] <- lapply(QUIC_child[cols_reverse], reverseCode, min=0, max=1)

#scoring
followup$QUIC_child_total <- apply(QUIC_child,1, sum)
followup$QUIC_child_parentalmonitoring <- apply(QUIC_child[cols_parentalmonitoring], 1,sum)
followup$QUIC_child_parentalenvironment <- apply(QUIC_child[cols_parentalenvironment], 1,sum)
followup$QUIC_child_parentalpredictability <- apply(QUIC_child[cols_parentalpredictability], 1,sum)
followup$QUIC_child_physiscalenvironment <- apply(QUIC_child[cols_physiscalenvironment], 1,sum)
followup$QUIC_child_safetyandsecurity <- apply(QUIC_child[cols_safetyandsecurity], 1,sum)
hist(followup$QUIC_child_total)


### ADOLESCENCE ###
#QUIC Scoring
QUIC_Adolescence <- followup %>%
  dplyr::select("QUIC_adol1":"QUIC_adol36")

#recode verbal responses (if not numbers)
QUIC_Adolescence[QUIC_Adolescence == "Yes"] <- as.numeric(1)
QUIC_Adolescence[QUIC_Adolescence == "No"] <- as.numeric(0)
QUIC_Adolescence[1:36] <- as.numeric(unlist(QUIC_Adolescence[1:36]))

cols_reverse <- c("QUIC_adol1", "QUIC_adol3", "QUIC_adol4", "QUIC_adol5", "QUIC_adol6", "QUIC_adol7", "QUIC_adol8",
                 "QUIC_adol12", "QUIC_adol13", "QUIC_adol15", "QUIC_adol26", "QUIC_adol34")

cols_parentalmonitoring <- c("QUIC_adol1", "QUIC_adol3", "QUIC_adol4", "QUIC_adol5", "QUIC_adol7", "QUIC_adol8",
                  "QUIC_adol12")

cols_parentalpredictability <- c("QUIC_adol2", "QUIC_adol6","QUIC_adol9", "QUIC_adol10", "QUIC_adol13","QUIC_adol14", "QUIC_adol15","QUIC_adol29","QUIC_adol30","QUIC_adol31", "QUIC_adol32","QUIC_adol33")

cols_parentalenvironment <- c("QUIC_adol16", "QUIC_adol17","QUIC_adol19", "QUIC_adol20", "QUIC_adol26","QUIC_adol27", "QUIC_adol28")

cols_physiscalenvironment <- c("QUIC_adol11", "QUIC_adol18",  "QUIC_adol24", "QUIC_adol25", "QUIC_adol34", "QUIC_adol35", "QUIC_adol36")

cols_safetyandsecurity <- c("QUIC_adol21", "QUIC_adol22", "QUIC_adol23")

# Reverse code
QUIC_Adolescence[cols_reverse] <- lapply(QUIC_Adolescence[cols_reverse], reverseCode, min=0, max=1)

#scoring
followup$QUIC_Adolescence_total <- apply(QUIC_Adolescence,1, sum)
followup$QUIC_Adolescence_parentalmonitoring <- apply(QUIC_Adolescence[cols_parentalmonitoring], 1,sum)
followup$QUIC_Adolescence_parentalpredictability <- apply(QUIC_Adolescence[cols_parentalpredictability], 1,sum)
followup$QUIC_Adolescence_parentalenvironment <- apply(QUIC_Adolescence[cols_parentalenvironment], 1,sum)
followup$QUIC_Adolescence_physiscalenvironment <- apply(QUIC_Adolescence[cols_physiscalenvironment], 1,sum)
followup$QUIC_Adolescence_safetyandsecurity <- apply(QUIC_Adolescence[cols_safetyandsecurity], 1,sum)
hist(followup$QUIC_Adolescence_total)

cor.test(followup$QUIC_child_total, followup$QUIC_Adolescence_total)
ggplot(data=followup, aes(x=QUIC_child_total, y=QUIC_Adolescence_total)) + geom_point() +
  geom_smooth(method="lm")

followup$QUIC_sum <- followup$QUIC_child_total + followup$QUIC_Adolescence_total
```

#DT (childhood + adolescence)
```{r}
### CHILDHOOD ###
#Deprivation Scoring
deprivation_child <- followup %>%
  dplyr::select("DT_child1_1":"DT_child25_1")

cols_reverse <- c("DT_child1_1", "DT_child2_1", "DT_child3_1", "DT_child4_1", "DT_child5_1", "DT_child6_1", "DT_child7_1", "DT_child10_1", "DT_child18_1", "DT_child19_1", "DT_child20_1", "DT_child21_1", "DT_child22_1", "DT_child23_1", "DT_child24_1", "DT_child25_1")

cols_emotionaldeprivation <- c("DT_child1_1", "DT_child2_1", "DT_child3_1", "DT_child4_1", "DT_child5_1", "DT_child6_1", "DT_child7_1")

cols_physicaldeprivation <- c("DT_child10_1", "DT_child11_1", "DT_child12_1", "DT_child13_1", "DT_child14_1", "DT_child15_1", "DT_child16_1", "DT_child17_1")

cols_cognitivedeprivation <- c("DT_child18_1", "DT_child19_1", "DT_child20_1", "DT_child21_1", "DT_child22_1", "DT_child23_1", "DT_child24_1", "DT_child25_1")

# Reverse code
deprivation_child[cols_reverse] <- lapply(deprivation_child[cols_reverse], reverseCode, min=1, max=4)

#scoring
followup$deprivation_child_total <- apply(deprivation_child,1, sum)
followup$deprivation_child_emotional <- apply(deprivation_child[cols_emotionaldeprivation], 1,sum)
followup$deprivation_child_physical <- apply(deprivation_child[cols_physicaldeprivation], 1,sum)
followup$deprivation_child_cognitive <- apply(deprivation_child[cols_cognitivedeprivation], 1,sum)
hist(followup$deprivation_child_total)

### ADOLESCENCE ###
#Deprivation Scoring
deprivation_Adolescence <- followup %>%
  dplyr::select("DT_adol1_1":"DT_adol25_1")

cols_reverse <- c("DT_adol1_1", "DT_adol2_1", "DT_adol3_1", "DT_adol4_1", "DT_adol5_1", "DT_adol6_1", "DT_adol7_1", "DT_adol10_1")

cols_emotionaldeprivation <- c("DT_adol1_1", "DT_adol2_1", "DT_adol3_1", "DT_adol4_1", "DT_adol5_1", "DT_adol6_1", "DT_adol7_1")

cols_physicaldeprivation <- c("DT_adol10_1", "DT_adol11_1", "DT_adol12_1", "DT_adol13_1", "DT_adol14_1", "DT_adol15_1", "DT_adol16_1", "DT_adol17_1")

cols_cognitivedeprivation <- c("DT_adol18_1", "DT_adol19_1", "DT_adol20_1", "DT_adol21_1", "DT_adol22_1", "DT_adol23_1", "DT_adol24_1", "DT_adol25_1")

# Reverse code
deprivation_Adolescence[cols_reverse] <- lapply(deprivation_Adolescence[cols_reverse], reverseCode, min=1, max=4)

#scoring
followup$deprivation_Adolescence_total <- apply(deprivation_Adolescence,1, sum)
followup$deprivation_Adolescence_emotional <- apply(deprivation_Adolescence[cols_emotionaldeprivation], 1,sum)
followup$deprivation_Adolescence_physical <- apply(deprivation_Adolescence[cols_physicaldeprivation], 1,sum)
followup$deprivation_Adolescence_cognitive <- apply(deprivation_Adolescence[cols_cognitivedeprivation], 1,sum)
hist(followup$deprivation_Adolescence_total)
cor.test(followup$deprivation_child_total, followup$deprivation_Adolescence_total, na.rm=TRUE)
ggplot(data=followup, aes(x=deprivation_child_total, y=deprivation_Adolescence_total)) + geom_point()+
  geom_smooth()

followup$deprivation_sum <- followup$deprivation_child_total + followup$deprivation_Adolescence_total

### CHILDHOOD ###
#Threat Scoring
threat_child <- followup %>%
  dplyr::select("DT_child26_1":"DT_child45_1")

cols_home_threat <- c("DT_child26_1","DT_child27_1","DT_child28_1","DT_child29_1","DT_child30_1","DT_child31_1","DT_child32_1","DT_child33_1","DT_child34_1","DT_child35_1","DT_child36_1","DT_child37_1")
cols_neighborhood_threat <- c("DT_child38_1","DT_child39_1","DT_child40_1","DT_child41_1","DT_child42_1","DT_child43_1","DT_child44_1","DT_child45_1")
followup$threat_childhood_total <- apply(threat_child,1, sum)
followup$threat_childhood_home <- apply(threat_child[cols_home_threat], 1,sum)
followup$threat_childhood_neighborhood <- apply(threat_child[cols_neighborhood_threat], 1,sum)
hist(followup$threat_childhood_total)

### ADOLESCENCE ###
#Threat Scoring
threat_adolescence <- followup %>%
  dplyr::select("DT_adol26_1":"DT_adol45_1")

cols_home_threat <- c("DT_adol26_1","DT_adol27_1","DT_adol28_1","DT_adol29_1","DT_adol30_1","DT_adol31_1","DT_adol32_1","DT_adol33_1","DT_adol34_1","DT_adol35_1","DT_adol36_1","DT_adol37_1")
cols_neighborhood_threat <- c("DT_adol38_1","DT_adol39_1","DT_adol40_1","DT_adol41_1","DT_adol42_1","DT_adol43_1","DT_adol44_1","DT_adol45_1")
followup$threat_adolescence_total <- apply(threat_adolescence,1, sum)
followup$threat_adolescence_home <- apply(threat_adolescence[cols_home_threat], 1,sum)
followup$threat_adolescence_neighborhood <- apply(threat_adolescence[cols_neighborhood_threat], 1,sum)
hist(followup$threat_adolescence_total)
ggplot(data=followup, aes(x=threat_childhood_total, y=threat_adolescence_total)) + geom_point()+
  geom_smooth()
cor.test(followup$threat_adolescence_total, followup$threat_childhood_total)
followup$Threat_sum <- followup$threat_childhood_total + followup$threat_adolescence_total
```

#STAI
```{r}
STAI <- followup %>%
  dplyr::select("STAI1_1":"STAI20_1")


cols_reverse <- c("STAI1_1","STAI3_1","STAI6_1","STAI7_1","STAI10_1","STAI13_1","STAI14_1","STAI16_1","STAI19_1")
STAI[cols_reverse] <- lapply(STAI[cols_reverse], reverseCode, min=1, max=4)


#if it is a simple subscore (i.e. no reverse coding or anything)
followup$STAI_total <- apply(STAI,1,sum)
hist(followup$STAI_total)
```

#CD-RISC
```{r}
CD.RISC <- followup %>%
  dplyr::select("CD.RISC1_1":"CD.RISC10_1")

followup$CD.RISC_total <- apply(CD.RISC,1,sum)
hist(followup$CD.RISC_total)
```

#HUMS (adolescent + current)
```{r}
### ADOLESCENT ###
#HUMS Scoring
HUMS_adolescent <- followup %>%
  dplyr::select("HUMS_adol1_1":"HUMS_adol13_1")

cols_healthy <- c("HUMS_adol3_1","HUMS_adol5_1","HUMS_adol6_1","HUMS_adol9_1","HUMS_adol13_1")
cols_unhealthy <- c("HUMS_adol1_1","HUMS_adol2_1","HUMS_adol4_1","HUMS_adol7_1","HUMS_adol8_1","HUMS_adol10_1","HUMS_adol11_1","HUMS_adol12_1")

followup$HUMS_adolescence_healthy <- apply(HUMS_adolescent[cols_healthy], 1,sum)
followup$HUMS_adolescence_unhealthy <- apply(HUMS_adolescent[cols_unhealthy], 1,sum)


### ADULT ###
#HUMS Scoring
HUMS_adult <- followup %>%
  dplyr::select("HUMS_current1_1":"HUMS_current13_1")

cols_healthy <- c("HUMS_current3_1","HUMS_current5_1","HUMS_current6_1","HUMS_current9_1","HUMS_current13_1")
cols_unhealthy <- c("HUMS_current1_1","HUMS_current2_1","HUMS_current4_1","HUMS_current7_1","HUMS_current8_1","HUMS_current10_1","HUMS_current11_1","HUMS_current12_1")

followup$HUMS_adult_healthy <- apply(HUMS_adult[cols_healthy], 1,sum)
followup$HUMS_adult_unhealthy <- apply(HUMS_adult[cols_unhealthy], 1,sum)
```

#CHAOS Scoring
```{r}
### CHILDHOOD ###
#CHAOS Scoring
CHAOS_child <- followup %>%
  dplyr::select("CHAOS_child1_1":"CHAOS_child15_1")

cols_reverse <- c("CHAOS_child1_1", "CHAOS_child2_1", "CHAOS_child4_1", "CHAOS_child7_1",
                   "CHAOS_child12_1", "CHAOS_child14_1","CHAOS_child15_1")

cols_shortform <- c("CHAOS_child4_1", "CHAOS_child6_1", "CHAOS_child10_1", "CHAOS_child13_1",
                   "CHAOS_child14_1", "CHAOS_child15_1")

# Reverse code
CHAOS_child[cols_reverse] <- lapply(CHAOS_child[cols_reverse], reverseCode, min=1, max=5)

followup$CHAOS_child_total <- apply(CHAOS_child,1, sum)
followup$CHAOS_child_shortform <- apply(CHAOS_child[cols_shortform],1, sum)
hist(followup$CHAOS_child_total)

### ADOLESCENCE ###
#CHAOS Scoring
CHAOS_Adolescence <- followup %>%
  dplyr::select("CHAOS_Adolescence1_1":"CHAOS_Adolescence15_1")

cols_reverse <- c("CHAOS_Adolescence1_1", "CHAOS_Adolescence2_1", "CHAOS_Adolescence4_1", "CHAOS_Adolescence7_1",
                   "CHAOS_Adolescence12_1", "CHAOS_Adolescence14_1","CHAOS_Adolescence15_1")

# Reverse code
CHAOS_Adolescence[cols_reverse] <- lapply(CHAOS_Adolescence[cols_reverse], reverseCode, min=1, max=5)

followup$CHAOS_Adolescence_total <- apply(CHAOS_Adolescence,1, sum)
hist(followup$CHAOS_Adolescence_total)

cor.test(followup$CHAOS_child_total, followup$CHAOS_Adolescence_total)
ggplot(data=followup, aes(x=CHAOS_child_total, y=CHAOS_Adolescence_total)) + geom_point() +
  geom_smooth()

followup$CHAOS_sum <- followup$CHAOS_child_total + followup$CHAOS_Adolescence_total
```

#AIMS Scoring
```{r}
AIMS <- followup %>%
  dplyr::select("AIMS_current1_1":"AIMS_current34_1")

followup$AIMS_current_total <- apply(AIMS,1, sum)

cor.test(followup$AIMS_current_total, followup$QUIC_sum)
hist(followup$AIMS_current_total)
```

#escapism scoring
```{r}
escapism_current <- followup %>%
  dplyr::select("Escapism_current1_1":"Escapism_current11_1")

cols_negative_escapism_current <- c("Escapism_current1_1","Escapism_current2_1","Escapism_current3_1","Escapism_current4_1","Escapism_current5_1","Escapism_current6_1")
  
cols_positive_escapism_current <- c("Escapism_current7_1","Escapism_current8_1","Escapism_current9_1","Escapism_current10_1","Escapism_current11_1")

followup$positive_escapism_current <- apply(escapism_current[cols_positive_escapism_current],1, sum)
followup$negative_escapism_current <- apply(escapism_current[cols_negative_escapism_current],1, sum)
hist(followup$positive_escapism_current)
hist(followup$negative_escapism_current)
cor.test(followup$AIMS_current_total, followup$negative_escapism_current)

#adolescent
escapism_adol <- followup %>%
  dplyr::select("Escampism_adol1_1":"Escapism_adol11_1")

cols_negative_escapism_adol <- c("Escampism_adol1_1","Escapism_adol2_1","Escapism_adol3_1","Escapism_adol4_1","Escapism_adol5_1","Escapism_adol6_1")
  
cols_positive_escapism_adol <- c("Escapism_adol7_1","Escapism_adol8_1","Escapism_adol9_1","Escapism_adol10_1","Escapism_adol11_1")

followup$positive_escapism_adol <- apply(escapism_adol[cols_positive_escapism_adol],1, sum)
followup$negative_escapism_adol <- apply(escapism_adol[cols_negative_escapism_adol],1, sum)
hist(followup$positive_escapism_adol)
hist(followup$negative_escapism_adol)
```
#SRQ
```{r}
SRQ_current <- followup %>%
  dplyr::select("SRQ_current1_1":"SRQ_current8_1")

cols_prosocialinteractions <- c("SRQ_current1_1","SRQ_current3_1","SRQ_current6_1","SRQ_current7_1","SRQ_current8_1")

cols_sociability <- c("SRQ_current2_1","SRQ_current4_1","SRQ_current5_1")

followup$SRQ_current_total <- apply(SRQ_current,1, sum)
followup$SRQ_current_prosocialinteractions <- apply(SRQ_current[cols_prosocialinteractions],1, sum)
followup$SRQ_current_sociability <- apply(SRQ_current[cols_sociability],1, sum)

#adol
SRQ_adol <- followup %>%
  dplyr::select("SQR_adol1_1":"SQR_adol8_1")

cols_prosocialinteractions <- c("SQR_adol1_1","SQR_adol3_1","SQR_adol6_1","SQR_adol7_1","SQR_adol8_1")

cols_sociability <- c("SQR_adol2_1","SQR_adol4_1","SQR_adol5_1")

followup$SRQ_adol_total <- apply(SRQ_adol,1, sum)
followup$SRQ_adol_prosocialinteractions <- apply(SRQ_adol[cols_prosocialinteractions],1, sum)
followup$SRQ_adol_sociability <- apply(SRQ_adol[cols_sociability],1, sum)
```

#AES
```{r}
AES <- followup %>%
  dplyr::select("AES1_1":"AES14_1")

cols_viseral <- c("AES3_1","AES4_1","AES7_1","AES11_1","AES12_1","AES13_1", "AES14_1")

cols_abstract <- c("AES1_1","AES2_1","AES5_1","AES6_1","AES8_1","AES9_1","AES10_1")

followup$AES_total <- apply(AES, 1, sum)
followup$AES_viseral <- apply(AES[cols_viseral],1, sum)
followup$AES_abstract <- apply(AES[cols_abstract],1, sum)
```

#write master file
```{r}
names(followup)[18] <- "ID"
names(ogsurveyresponses)[18] <- "ID"
master <- merge(followup, ogsurveyresponses, by="ID")
#some missing values in the ogBMRQ_goldMSI df
setdiff(followup$ID,master$ID)
names(MET_scores)[1]<-"ID"
master <- merge(master,MET_scores)

write.csv(master, file="../data/SLfollowupscored.csv")
```
