---
title: "2_analysis"
author: "Nick Kathios"
date: '2022-10-21'
output: html_document
---
```{r}
library(tidyverse)
library(lme4)
library(mediation)
library(lmerTest)
library(performance)
library(sjPlot)
library(boot)
```

#read in data
```{r}
scored_data <- read.csv(file="../data/pleasing-displeasing_followup/scored_data.csv")
master <- read.csv(file="../data/pleasing-displeasing_followup/pleasing_displeasing_scored.csv")
matched_data <- read.csv("../data/pleasing-displeasing_followup/matched_data.csv")
```

#histograms
```{r}
scored_data$threat_adolescence_total
ggplot(scored_data, aes(x=threat_adolescence_total)) +
         geom_histogram() +
  xlab("Threat Adolescent Score") +
  ylab("Frequency")

ggplot(scored_data, aes(x=threat_childhood_total, y= threat_adolescence_total)) +
  geom_point()+
  geom_smooth(method="lm") +
  xlab("Childhood Threat Score") +
  ylab("Adolescent Threat Score")

cor.test(all_scored$Gold_perceptualabilities, all_scored$THre_sum, na.rm=TRUE)
```

#cleaning original data before merge
```{r}
master <- master[-1]
names(master)[1] <- "ID"
names(master)[10:21] <- c('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J','K','L')
names(master)[22:31] <-c('IADS105','IADS110','IADS220','IADS283','IADS351','IADS353',
                         'IADS423','IADS502','IADS717','IADS730')
names(master)[32:39] <- c('Envi1','Envi2','Envi3','Envi4','Envi5','Envi6','Envi7','Envi8')

just_ratings<-master[10:39] -4
cleaned <- cbind(master[1], just_ratings)
cleaned <- cbind(cleaned, master[267])

derived <- cleaned[1:13]
derivedstims <- pivot_longer(derived, A:L, names_to = "stim_name", values_to = "rating" )

IADS <- cleaned[14:23]
IADS <- cbind(cleaned[1], IADS)
IADS <- cbind(cleaned[32], IADS)
IADS_stims <- pivot_longer(IADS, IADS105:IADS730, names_to = "stim_name", values_to = "rating" )

envi <- just_ratings[23:30]
envi <- cbind(cleaned[1], envi)
envi_stims <- pivot_longer(envi, Envi1:Envi8, names_to = "stim_name", values_to = "rating" )
#changing stim names for pleasing/displeasing comparisons
names(derived)[2:13] <- c("Displeasing1", "Displeasing2", "Pleasing3","Displeasing4",
                          "Pleasing5", "Pleasing6", "Displeasing7","Displeasing8",
                          "Pleasing9", "Pleasing10", "Pleasing11", "Displeasing12")

derived_plsdispls <- pivot_longer(derived, !ID, names_to = "soundID", values_to = "rating" )

derived_plsdispls$stim_name <- gsub("[0-9]", "", derived_plsdispls$soundID)

names(IADS)[3:12] <- c("Displeasing1", "Pleasing2", "Pleasing3", "Displeasing4",
                          "Pleasing5", "Pleasing6", "Displeasing7","Displeasing8",
                          "Pleasing9", "Displeasing10")
IADS_plsdispls <- pivot_longer(IADS, !PASS_total:ID, names_to = "soundID", values_to = "rating")

IADS_plsdispls$stim_name <- gsub("[0-9]", "", IADS_plsdispls$soundID)

names(envi)[2:9] <- c("Displeasing1", "Displeasing2", "Pleasing3", "Pleasing4",
                          "Pleasing5", "Pleasing6", "Displeasing7","Displeasing8")
envi_plsdispls <- pivot_longer(envi, !ID, names_to = "soundID", values_to = "rating")
envi_plsdispls$stim_name <- gsub("[0-9]", "", envi_plsdispls$soundID)
```

#UPDATE BASED ON WHERE Q IS IN DF
```{r}
names(scored_data)[20] <- "ID"
names(matched_data)[3] <- "ID"
```

#merge the datasets
```{r}
all_scored <- merge(master, scored_data, by.x="ID", by.y="ID")
digital <-merge(derived_plsdispls, all_scored, by.x="ID", by.y="ID")
digital_pleasing <- subset(digital, stim_name=="Pleasing")
digital_displeasing <- subset(digital, stim_name=="Displeasing")
IADS<-merge(IADS_plsdispls, all_scored, by.x="ID", by.y="ID")
IADS_pleasing <- subset(IADS, stim_name=="Pleasing")
names(IADS_pleasing)[2] <-"PASS_total"
IADS_displeasing <- subset(IADS, stim_name=="Displeasing")
envi <- merge(envi_plsdispls, all_scored, by.x="ID", by.y="ID")
envi_pleasing <- subset(envi, stim_name=="Pleasing")
envi_displeasing <- subset(envi, stim_name=="Displeasing")
matched_data <- merge(matched_data, all_scored, by.x="ID", by.y="ID")

write.csv(all_scored, "../data/all_scored.csv")
```

#H1
```{r}
m1 <- lmer(rating ~ CHAOS_Adolescence_total + threat_adolescence_total + deprivation_Adolescence_total + QUIC_Adolescence_total + PASS_total.x + (1 | ID) + (1 | soundID), data=IADS_displeasing)

m1 <- lmer(rating ~ QUIC_sum + CHAOS_sum + deprivation_sum + Threat_sum + PASS_total + (1 | ID) + (1 | soundID), data=digital_pleasing)
#multicollinearity checks
check_collinearity(m1)
summary(m1)

m1 <- lmer(rating ~ QUIC_sum + CHAOS_sum + deprivation_sum + Threat_sum + STAI_total + (1 | ID) + (1 | soundID), data=digital_pleasing)
#multicollinearity checks
check_collinearity(m1)
summary(m1)

m2 <- lmer(scale(rating) ~ scale(QUIC_sum) + scale(CHAOS_sum) + scale(deprivation_sum) + scale(Threat_sum) + scale(PASS_total) + (1 | ID) + (1 | soundID), data=digital_displeasing)
#multicollinearity checks
check_collinearity(m2)
summary(m2)
#plot results
plot_model(m2, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("Displeasing Digitally-Generated")

m2 <- lmer(scale(rating) ~ scale(CHAOS_child_total) + scale(threat_childhood_total) + scale(deprivation_child_total) + scale(QUIC_child_total) + scale(STAI_total) + scale(PASS_total.x) + (1| ID) + (1 | soundID), data=IADS_displeasing)
summary(m2)

m2 <- lmer(scale(rating) ~ scale(CHAOS_child_total) + scale(threat_childhood_total) + scale(deprivation_child_total) + scale(QUIC_child_total) + scale(STAI_total) + scale(PASS_total) + (1| ID) + (1 | soundID), data=digital_displeasing)
summary(m2)

#plot results
plot_model(m2, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("Displeasing Digitally-Generated")

#timing follow-up - PAS
m2t <- lmer((rating) ~ (CHAOS_Adolescence_total) + (CHAOS_child_total) + (PASS_total) + STAI_total+ (1| ID) + (1 | soundID), data=digital_displeasing)
check_collinearity(m2t)
summary(m2t)
#plot results
plot_model(m2t, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("Displeasing Digitally-Generated")

#timing follow-up - STAI
m2t <- lmer(scale(rating) ~ scale(CHAOS_Adolescence_total) + scale(CHAOS_child_total) + scale(STAI_total) + (1| ID) + (1 | soundID), data=digital_displeasing)
check_collinearity(m2t)
summary(m2t)
#plot results
plot_model(m2t, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("Displeasing Digitally-Generated")

m3 <- lmer(scale(rating) ~ scale(QUIC_sum) + scale(CHAOS_sum) + scale(deprivation_sum) + scale(Threat_sum)+ scale(PASS_total)+ (1 | ID) + (1 | soundID), data=IADS_pleasing)
summary(m3)
#plot results
plot_model(m3, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("Pleasing IADS Sounds")

m3 <- lmer(scale(rating) ~ scale(QUIC_sum) + scale(CHAOS_sum) + scale(deprivation_sum) + scale(Threat_sum)+ scale(STAI_total)+ (1 | ID) + (1 | soundID), data=IADS_pleasing)
summary(m3)
#plot results
plot_model(m3, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("Pleasing IADS Sounds")

#timing follow-up
m3t <- lmer(rating ~ threat_childhood_total + threat_adolescence_total + PASS_total + (1 | ID) + (1 | soundID), data=IADS_pleasing)
check_collinearity(m3t)
summary(m3t)

m3t <- lmer(rating ~ threat_childhood_total + threat_adolescence_total + STAI_total + (1 | ID) + (1 | soundID), data=IADS_pleasing)
check_collinearity(m3t)
summary(m3t)

m4 <- lmer(rating ~ QUIC_sum + CHAOS_sum + deprivation_sum + Threat_sum + PASS_total.x+ (1 | ID)+ (1 | soundID), data=IADS_displeasing)
summary(m4)
m4 <- lmer(rating ~ QUIC_sum + CHAOS_sum + deprivation_sum + Threat_sum + STAI_total+ (1 | ID)+ (1 | soundID), data=IADS_displeasing)
summary(m4)

m5 <- lmer(rating ~ QUIC_sum + deprivation_sum + Threat_sum + (1 | ID)+ (1 | soundID), data=envi_pleasing)
summary(m5)

m6 <- lmer(rating ~ QUIC_sum + deprivation_sum + Threat_sum + (1 | ID) + (1 | soundID), data=envi_displeasing)
summary(m6)
```

#H2
```{r}
#MBEA
m1 <- lm(MBEA_total ~ QUIC_sum + CHAOS_sum + deprivation_sum + Threat_sum + PASS_total, data=all_scored)
summary(m1)
#plot results
plot_model(m1, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("MBEA Scores")

m1 <- lm(MBEA_total ~ QUIC_sum + CHAOS_sum + deprivation_sum + Threat_sum + STAI_total, data=all_scored)
summary(m1)
#plot results
plot_model(m1, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("MBEA Scores")
all_scored$Gold_
#timing follow-up
m1t <- lm(MBEA_total ~ CHAOS_child_total + CHAOS_Adolescence_total + threat_childhood_total + threat_adolescence_total + PASS_total, data=all_scored)
check_collinearity(m1t)
summary(m1t)

#plot results
plot_model(m1t, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("MBEA Scores")
m1t <- lm(MBEA_total ~ CHAOS_child_total + CHAOS_Adolescence_total + threat_childhood_total + threat_adolescence_total + STAI_total + Gold_musicaltraining, data=all_scored)
check_collinearity(m1t)
summary(m1t)
#plot results
plot_model(m1t, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("MBEA Scores")

m2 <- lm(BAT_total ~  QUIC_sum + CHAOS_sum + deprivation_sum + Threat_sum + PASS_total, data=all_scored)
summary(m2)
check_collinearity(m2)

m2t <- lm(BAT_total ~ CHAOS_child_total + CHAOS_Adolescence_total + STAI_total, data=all_scored)
summary(m2t)


## updated streamline
#CHAOS childhood negative correlation
m1 <- lm(MBEA_total ~ CHAOS_child_total + threat_childhood_total + deprivation_child_total + QUIC_child_total + PASS_total +STAI_total + Gold_musicaltraining, data=all_scored)
check_collinearity(m1)
summary(m1)
plot_model(m1, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("MBEA Scores")

m1 <- lm(MBEA_total ~ CHAOS_child_total + CHAOS_Adolescence_total + threat_adolescence_total + threat_childhood_total + PASS_total + STAI_total + Gold_musicaltraining, data=all_scored)
summary(m1)
check_collinearity(m1)
plot_model(m1, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("MBEA Scores")

#Threat adolescent positive correlation
m1 <- lm(MBEA_total ~  CHAOS_Adolescence_total + threat_adolescence_total + deprivation_Adolescence_total + QUIC_Adolescence_total + PASS_total + STAI_total + Gold_musicaltraining, data=all_scored)
summary(m1)
plot_model(m1, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("MBEA Scores")

m1 <- lm(MBEA_total ~ threat_childhood_total + threat_adolescence_total +PASS_total + Gold_musicaltraining, data=all_scored)
summary(m1)
plot_model(m1, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("MBEA Scores")

#QUIC Adolescent positive correlation
m1 <- lm(BAT_total ~ CHAOS_child_total + threat_childhood_total + deprivation_child_total + QUIC_child_total + PASS_total + Gold_musicaltraining, data=all_scored)
summary(m1)
plot_model(m1, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("MBEA Scores")

m1 <- lm(MBEA_total ~  CHAOS_Adolescence_total + threat_adolescence_total + deprivation_Adolescence_total + QUIC_Adolescence_total + PASS_total + Gold_musicaltraining, data=all_scored)
summary(m1)
plot_model(m1, show.values = TRUE,vline.color = "lightgrey") +
  ggtitle("MBEA Scores")

m1 <- lm(BAT_total ~ STAI_total + Gold_musicaltraining, data=all_scored)
summary(m1)
```

#H3
```{r}
m1 <- lm(BMRQ_total ~ QUIC_sum  + deprivation_sum + Threat_sum + CHAOS_sum, data=all_scored)
summary(m1)
```

#exploratory -- bmrq subscale analyses
```{r}
cor.test(all_scored$QUIC_Adolescence_total, all_scored$STAI_total)

ggplot(all_scored, aes(x=What.is.your.age., y=AES_total)) +
  geom_point() +
  geom_smooth(method="lm") +
  theme_light()+
  ylab("AES Total Score") +
  xlab("Age")

##cor tests for bmrq total
cor.test(all_scored$CHAOS_sum, all_scored$BMRQ_total)
cor.test(all_scored$QUIC_sum, all_scored$BMRQ_total)
cor.test(all_scored$Threat_sum, all_scored$BMRQ_total)
cor.test(all_scored$deprivation_sum, all_scored$BMRQ_total)

## eBMRQ subscales + ELA measures
cor.test(all_scored$CHAOS_sum, all_scored$BMRQ_absorption)
cor.test(all_scored$QUIC_sum, all_scored$BMRQ_absorption)
cor.test(all_scored$Threat_sum, all_scored$BMRQ_absorption)
cor.test(all_scored$deprivation_sum, all_scored$BMRQ_absorption)
m1 <-lm(BMRQ_absorption ~ CHAOS_sum  + QUIC_sum +  + deprivation_sum + Threat_sum, data=all_scored)
summary(m1) 

cor.test(all_scored$CHAOS_sum, all_scored$BMRQ_emotion)
cor.test(all_scored$QUIC_sum, all_scored$BMRQ_emotion)
cor.test(all_scored$Threat_sum, all_scored$BMRQ_emotion)
cor.test(all_scored$deprivation_sum, all_scored$CHAOS_child_total)
m1 <-lm(BMRQ_emotion ~ CHAOS_sum  + QUIC_sum + deprivation_sum + Threat_sum, data=all_scored)
summary(m1) 

cor.test(all_scored$CHAOS_sum, all_scored$BMRQ_socialreward)
cor.test(all_scored$QUIC_sum, all_scored$BMRQ_socialreward)
cor.test(all_scored$Threat_sum, all_scored$BMRQ_socialreward)
cor.test(all_scored$deprivation_sum, all_scored$BMRQ_socialreward)
summary(m1)

cor.test(all_scored$CHAOS_sum, all_scored$BMRQ_musicseek)
cor.test(all_scored$QUIC_sum, all_scored$BMRQ_musicseek)
cor.test(all_scored$Threat_sum, all_scored$BMRQ_musicseek)
cor.test(all_scored$deprivation_sum, all_scored$BMRQ_musicseek)

cor.test(all_scored$CHAOS_sum, all_scored$BMRQ_moodreg)
cor.test(all_scored$QUIC_sum, all_scored$BMRQ_moodreg)
cor.test(all_scored$Threat_sum, all_scored$BMRQ_moodreg)
cor.test(all_scored$deprivation_sum, all_scored$BMRQ_moodreg)


cor.test(all_scored$CHAOS_sum, all_scored$BMRQ_sensorimotor)
cor.test(all_scored$QUIC_sum, all_scored$BMRQ_sensorimotor)
cor.test(all_scored$Threat_sum, all_scored$BMRQ_sensorimotor)
cor.test(all_scored$deprivation_sum, all_scored$BMRQ_sensorimotor)

## childhood measures
cor.test(all_scored$CHAOS_child_total, all_scored$BMRQ_absorption)
cor.test(all_scored$QUIC_child_total, all_scored$BMRQ_absorption)
cor.test(all_scored$threat_childhood_total, all_scored$BMRQ_absorption)
cor.test(all_scored$deprivation_child_total, all_scored$BMRQ_absorption)
m1 <-lm(BMRQ_absorption ~ CHAOS_sum  + QUIC_sum + deprivation_sum + Threat_sum, data=all_scored)
summary(m1) 

cor.test(all_scored$CHAOS_child_total, all_scored$BMRQ_emotion)
cor.test(all_scored$QUIC_child_total, all_scored$BMRQ_emotion)
cor.test(all_scored$threat_childhood_total, all_scored$BMRQ_emotion)
cor.test(all_scored$deprivation_child_total, all_scored$BMRQ_emotion)
m1 <-lm(BMRQ_emotion ~ CHAOS_sum  + QUIC_sum + deprivation_sum + Threat_sum, data=all_scored)
summary(m1) 

cor.test(all_scored$CHAOS_child_total, all_scored$BMRQ_socialreward)
cor.test(all_scored$QUIC_child_total, all_scored$BMRQ_socialreward)
cor.test(all_scored$threat_childhood_total, all_scored$BMRQ_socialreward)
cor.test(all_scored$deprivation_child_total, all_scored$BMRQ_socialreward)
summary(m1)

cor.test(all_scored$CHAOS_child_total, all_scored$BMRQ_musicseek)
cor.test(all_scored$QUIC_child_total, all_scored$BMRQ_musicseek)
cor.test(all_scored$threat_childhood_total, all_scored$BMRQ_musicseek)
cor.test(all_scored$deprivation_child_total, all_scored$BMRQ_musicseek)

cor.test(all_scored$CHAOS_child_total, all_scored$BMRQ_moodreg)
cor.test(all_scored$QUIC_child_total, all_scored$BMRQ_moodreg)
cor.test(all_scored$threat_childhood_total, all_scored$BMRQ_moodreg)
cor.test(all_scored$deprivation_child_total, all_scored$BMRQ_moodreg)

cor.test(all_scored$CHAOS_child_total, all_scored$BMRQ_sensorimotor)
cor.test(all_scored$QUIC_child_total, all_scored$BMRQ_sensorimotor)
cor.test(all_scored$threat_childhood_total, all_scored$BMRQ_sensorimotor)
cor.test(all_scored$deprivation_child_total, all_scored$BMRQ_sensorimotor)
```

```{r}
m1 <- lm(BMRQ_moodreg ~ CHAOS_sum + QUIC_sum + deprivation_sum + Threat_sum + PASS_total + BMRQ_absorption, data=all_scored)
summary(m1)
#HUMS - both adolescent + current
cor.test(all_scored$PASS_total, all_scored$STAI_total)
all_scored$Gold_musicaltraining
#use this code below when there's missing data and mediation can't run:
all_scored_allSTAI <- all_scored[complete.cases(all_scored$STAI_total),]
all_scored_allCDRISC <- all_scored[complete.cases(all_scored$CD.RISC_total),]
all_scored_allPASS <- all_scored[complete.cases(all_scored$PASS_total),]
m1 <- lm(HUMS_adolescence_unhealthy ~ CHAOS_sum + QUIC_sum + deprivation_sum + Threat_sum, data=all_scored_allPASS)
summary(m1)
m1m <- lm(HUMS_adolescence_unhealthy ~ CHAOS_sum + QUIC_sum + (deprivation_sum) + (Threat_sum) + (PASS_total), data=all_scored_allPASS)
fit.mediator=lm((CD.RISC_total)~(QUIC_sum),all_scored_allCDRISC)
summary(fit.mediator)

summary(m1m)
mediate <- mediate(m1, m1m, boot = TRUE, treat = "QUIC_sum", mediator = "PASS_total")
summary(mediate)

m1t <- lm(HUMS_adolescence_unhealthy ~ QUIC_child_total + QUIC_Adolescence_total, data=all_scored)
summary(m1)

m1 <- lm(HUMS_adolescence_unhealthy ~ QUIC_child_total + CHAOS_child_total + deprivation_child_total + threat_childhood_total, data=all_scored)
summary(m1t)

m1 <- lm(HUMS_adolescence_unhealthy ~ QUIC_Adolescence_total + CHAOS_Adolescence_total + deprivation_Adolescence_total + threat_adolescence_total, data=all_scored)
summary(m1)

m2 <- lm(HUMS_adult_unhealthy ~ QUIC_sum + CHAOS_sum + deprivation_sum + Threat_sum, data=all_scored)
summary(m2)

m2 <- lm(HUMS_adult_unhealthy ~ QUIC_Adolescence_total + CHAOS_Adolescence_total + deprivation_Adolescence_total + threat_adolescence_total, data=all_scored)
summary(m2)

m2 <- lm(HUMS_adult_unhealthy ~ QUIC_child_total + CHAOS_child_total + deprivation_child_total + threat_childhood_total, data=all_scored)
summary(m2)

m1 <- lm(HUMS_adolescence_healthy ~ QUIC_sum + CHAOS_sum + deprivation_sum + Threat_sum, data=all_scored)
summary(m1)

m1 <- lm(HUMS_adolescence_healthy ~ QUIC_Adolescence_total + CHAOS_Adolescence_total + deprivation_Adolescence_total + threat_adolescence_total, data=all_scored)
summary(m1)

m1 <- lm(HUMS_adolescence_healthy ~ QUIC_child_total + CHAOS_child_total + deprivation_child_total + threat_childhood_total, data=all_scored)
summary(m1)

m1 <- lm(HUMS_adult_healthy ~ QUIC_sum + CHAOS_sum + deprivation_sum + Threat_sum, data=all_scored)
summary(m1)

m1 <- lm(HUMS_adult_healthy ~ QUIC_Adolescence_total + CHAOS_Adolescence_total + deprivation_Adolescence_total + threat_adolescence_total, data=all_scored)
summary(m1)

m1 <- lm(HUMS_adult_healthy ~ QUIC_child_total + CHAOS_child_total + deprivation_child_total + threat_childhood_total, data=all_scored)
summary(m1)
### For all identified relationships, test mediators of CD-RISC + musical training ###

anhedonics <- matched_data %>%
  subset(group=="Musical Anhedonics")

matched_controls <- matched_data %>%
  subset(group=="Matched Controls")

t.test(anhedonics$deprivation_Adolescence_emotional, matched_controls$deprivation_Adolescence_emotional)

## separate timing / dimensionality modeling stuff with other hypotheses ##
## DIGITALLY GENERATED SOUDNS
#pleasing
#just childhood dimensions
m1 <- lmer(rating ~ QUIC_child_total + CHAOS_child_total + deprivation_child_total + threat_childhood_total + (1 | ID) + (1 | soundID), data=digital_pleasing)
summary(m1)

#just adolescence dimensions
m1 <- lmer(rating ~ QUIC_Adolescence_total + CHAOS_Adolescence_total + deprivation_Adolescence_total + threat_adolescence_total + (1 | ID) + (1 | soundID), data=digital_pleasing)
summary(m1)

#displeasing
#just childhood dimensions
m1 <- lmer(rating ~ QUIC_child_total + CHAOS_child_total + deprivation_child_total + threat_childhood_total +(1 | ID) + (1 | soundID), data=digital_displeasing)
summary(m1)
# mediation
m1m <- lmer(rating ~ QUIC_child_total + CHAOS_child_total + deprivation_child_total + threat_childhood_total + STAI_total + (1 | ID) + (1 | soundID), data=digital_displeasing)
summary(m1m)

#just adolescence dimensions
m1 <- lmer(rating ~ QUIC_Adolescence_total + CHAOS_Adolescence_total + deprivation_Adolescence_total + threat_adolescence_total + (1 | ID) + (1 | soundID), data=digital_displeasing)
summary(m1)
## directly pitting timing against each other  ##
m1 <- lmer(rating ~ CHAOS_child_total + CHAOS_Adolescence_total  + (1 | ID) + (1 | soundID), data=digital_displeasing)
summary(m1)


### IADS SOUNDS
#pleasing
m1 <- lmer(rating ~ QUIC_child_total + CHAOS_child_total + deprivation_child_total + threat_childhood_total + (1 | ID) + (1 | soundID), data=IADS_pleasing)
summary(m1)

m1 <- lmer(rating ~ QUIC_Adolescence_total + CHAOS_Adolescence_total + deprivation_Adolescence_total + threat_adolescence_total + (1 | ID) + (1 | soundID), data=IADS_pleasing)
summary(m1)

#displeasing
m1 <- lmer(rating ~ QUIC_child_total + CHAOS_child_total + deprivation_child_total + threat_childhood_total + (1 | ID) + (1 | soundID), data=IADS_displeasing)
summary(m1)

m1 <- lmer(rating ~ QUIC_Adolescence_total + CHAOS_Adolescence_total + deprivation_Adolescence_total + threat_adolescence_total + (1 | ID) + (1 | soundID), data=IADS_displeasing)
summary(m1)
```