---
title: "3_validation"
author: "Nick Kathios"
date: '2022-10-31'
output: html_document
---
#load packages
```{r}
library(tidyverse)
library(psych)
library(corrplot)
library(moments)
source("reverseCode.R")
library(psych)
library(EFAtools)
library(EFA.dimensions)
library(corrplot)
```
#read in data
```{r}
data <- read.csv(file='../data/pleasing-displeasing_followup/scored_data.csv')
all_scored<-read.csv(file='../data/all_scored.csv')
MH <- read.csv(file='../data/pleasing-displeasing_followup/scored_data.csv') %>%
  dplyr::select("M.H1_1":"M.H35_1")

cols_reverse <- c("M.H6_1","M.H7_1","M.H12_1","M.H14_1","M.H17_1","M.H18_1","M.H20_1","M.H23_1","M.H29_1","M.H30_1",
                  "M.H32_1")
MH[cols_reverse] <- lapply(MH[cols_reverse], reverseCode, min=1, max=7)
#removing check questions
updateMH <- MH[-c(32:34)]
```

#determine how many factors to use
```{r}
#McDonald Omega Test
fa.none <- psych::fa(r=updateMH, 
 nfactors = 30, 
  covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=1000,  
 rotate="oblimin") # no rotation

print(fa.none)

fa.diagram(fa.none)

SL_transformation <- EFAtools::SL(fa.none)
SL_transformation <- SL_transformation[[1]]

omega <-omega(SL_transformation, nfactors=7,n.iter=1,p=.05,poly=FALSE,key=NULL,
    flip=TRUE,digits=2, title="Omega",sl=TRUE,labels=NULL,
    plot=TRUE)

summary(omega)

#extracting factors
#FA w/ one factor
fa.none <- psych::fa(r=updateMH, 
 nfactors = 1, 
  covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100,  
 rotate="varimax")

#parallel analysis on residual to find factor #
residual <- fa.none[["residual"]]
parallel <- fa.parallel(residual) #suggests 4 factors
MAP <- vss(residual) #suggests 5 factors
MAP <- MAP[["map"]]
print(MAP)

fafitfree <- fa(residual,nfactors = ncol(residual), rotate = "oblimin",covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100)
n_factors <- length(fafitfree$e.values)
scree     <- data.frame(
  Factor_n =  as.factor(1:n_factors), 
  Eigenvalue = fafitfree$e.values)

ggplot(scree, aes(x = Factor_n, y = Eigenvalue, group = 1)) + 
  geom_point() + geom_line() +
  xlab("Number of factors") +
  ylab("Initial eigenvalue") +
  labs( title = "Scree Plot", 
        subtitle = "(Based on the unreduced correlation matrix)")+
  geom_line(y=1,color="red")

#item reduction on this factor structure
fa.none <- psych::fa(r=updateMH, 
 nfactors = 7, 
  covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100,  
 rotate="oblimin") # no rotation
summary(fa.none)
SL_transformation <- EFAtools::SL(fa.none)
SL_transformation <- SL_transformation[[2]]
SL_transformation

#remove items
updateMH <- dplyr::select(updateMH, -c("M.H17_1", "M.H20_1", "M.H18_1","M.H13_1","M.H19_1","M.H23_1",
                                       "M.H27_1"))
alpha <- alpha(updateMH)
summary(alpha)
#determine new no. of factors
#FA w/ one factor
fa.none <- psych::fa(r=updateMH, 
 nfactors = 1, 
  covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100,  
 rotate="varimax")

#parallel analysis on residual to find factor #
residual <- fa.none[["residual"]]
parallel <- fa.parallel(residual)
MAP <- vss(residual)
MAP <- MAP[["map"]]
print(MAP)

fafitfree <- fa(residual,nfactors = ncol(residual), rotate = "oblimin",covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100)
n_factors <- length(fafitfree$e.values)
scree     <- data.frame(
  Factor_n =  as.factor(1:n_factors), 
  Eigenvalue = fafitfree$e.values)

ggplot(scree, aes(x = Factor_n, y = Eigenvalue, group = 1)) + 
  geom_point() + geom_line() +
  xlab("Number of factors") +
  ylab("Initial eigenvalue") +
  labs( title = "Scree Plot", 
        subtitle = "(Based on the unreduced correlation matrix)")+
  geom_line(y=1,color="red")

#item reduction on this factor structure
fa.none <- psych::fa(r=updateMH, 
 nfactors = 6, 
  covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100,  
 rotate="oblimin") # no rotation
summary(fa.none)
SL_transformation <- EFAtools::SL(fa.none)
SL_transformation <- SL_transformation[[2]]
SL_transformation

#run again
updateMH <- dplyr::select(updateMH, -c("M.H15_1", "M.H24_1"))
alpha <- alpha(updateMH)
summary(alpha)
#determine new no. of factors
#FA w/ one factor
fa.none <- psych::fa(r=updateMH, 
 nfactors = 1, 
  covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100,  
 rotate="varimax")

#parallel analysis on residual to find factor #
residual <- fa.none[["residual"]]
parallel <- fa.parallel(residual)
MAP <- vss(residual)
MAP <- MAP[["map"]]
print(MAP)

fafitfree <- fa(residual,nfactors = ncol(residual), rotate = "oblimin",covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100)
n_factors <- length(fafitfree$e.values)
scree     <- data.frame(
  Factor_n =  as.factor(1:n_factors), 
  Eigenvalue = fafitfree$e.values)

ggplot(scree, aes(x = Factor_n, y = Eigenvalue, group = 1)) + 
  geom_point() + geom_line() +
  xlab("Number of factors") +
  ylab("Initial eigenvalue") +
  labs( title = "Scree Plot", 
        subtitle = "(Based on the unreduced correlation matrix)")+
  geom_line(y=1,color="red") #suggests 7 factors

#item reduction on this factor structure
fa.none <- psych::fa(r=updateMH, 
 nfactors = 7, 
  covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100,  
 rotate="oblimin") # no rotation
summary(fa.none)
SL_transformation <- EFAtools::SL(fa.none)
SL_transformation <- SL_transformation[[2]]
SL_transformation

#run again
updateMH <- dplyr::select(updateMH, -c("M.H22_1", "M.H31_1"))
alpha <- alpha(updateMH)
summary(alpha)
#determine new no. of factors
#FA w/ one factor
fa.none <- psych::fa(r=updateMH, 
 nfactors = 1, 
  covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100,  
 rotate="varimax")

#parallel analysis on residual to find factor #
residual <- fa.none[["residual"]]
parallel <- fa.parallel(residual)
MAP <- vss(residual)
MAP <- MAP[["map"]]
print(MAP)

fafitfree <- fa(residual,nfactors = ncol(residual), rotate = "oblimin",covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100)
n_factors <- length(fafitfree$e.values)
scree     <- data.frame(
  Factor_n =  as.factor(1:n_factors), 
  Eigenvalue = fafitfree$e.values)

ggplot(scree, aes(x = Factor_n, y = Eigenvalue, group = 1)) + 
  geom_point() + geom_line() +
  xlab("Number of factors") +
  ylab("Initial eigenvalue") +
  labs( title = "Scree Plot", 
        subtitle = "(Based on the unreduced correlation matrix)")+
  geom_line(y=1,color="red")

#item reduction on this factor structure
fa.none <- psych::fa(r=updateMH, 
 nfactors = 5, 
  covar = FALSE, SMC = TRUE,
 fm="ml", 
 max.iter=100,  
 rotate="oblimin") # no rotation
summary(fa.none)
SL_transformation <- EFAtools::SL(fa.none)
SL_transformation <- SL_transformation[[2]]
SL_transformation

scores <- factor.scores(as.matrix(updateMH), SL_transformation, method="components")
scores <- scores$scores
scores <- cbind(data[20], scores)
names(scores)[1] <- "ID"
full <- merge(scores, all_scored)
full$Gold_musicalsophistication
```

#corrplot
```{r}
#M@HR + GoldMSI
#gather variables of interest
variables = dplyr::select(full, 
                          g, F1, F2, F3, F4, F5, 
                          Gold_activeengagement, Gold_perceptualabilities, Gold_musicaltraining, Gold_singingabilities, 
                          Gold_emotion, Gold_musicalsophistication)
output = corr.test(variables)

corr_matrix = output$r
p_matrix <- output$p

colnames(corr_matrix) <- c('M@H-R General Score', 'Caregiver Beliefs', 'Caregiver Singingg', 'Attitude to Childhood Music', 'Home Music Associations', 'Music-Making Tendencies',
                           'GoldMSI Active Engagement', "GoldMSI Perceptual Abilities", "GoldMSI Musical Training", "GoldMSI Singing Abilities", "GoldMSI Emotion", "GoldMSI Musical Sophistication")
rownames(corr_matrix) <- c('M@H-R General Score', 'Caregiver Beliefs', 'Caregiver Singingg', 'Attitude to Childhood Music', 'Home Music Associations', 'Music-Making Tendencies',
                           'GoldMSI Active Engagement', "GoldMSI Perceptual Abilities", "GoldMSI Musical Training", "GoldMSI Singing Abilities", "GoldMSI Emotion", "GoldMSI Musical Sophistication")

pdf(file = "../figures/pleasing:displeasing_followup/BMRQ_corrplot_totals.pdf")

corrplot(corr_matrix, p.mat = p_matrix, insig = "label_sig",
         sig.level = c(0.001,0.01,0.05), pch.cex=0.9, pch.col = "black", tl.col = "black", type="lower",tl.srt =45, 
         col=colorRampPalette(c("darkblue","white","red"))(100),cl.lim=c(0,1))

#M@HR + eBMRQ
#generate correlation matrix
#gather variables of interest
variables = dplyr::select(full, 
                          g, F1, F2, F3, F4, F5, 
                          BMRQ_total, BMRQ_moodreg, BMRQ_emotion, BMRQ_socialreward,
                          BMRQ_absorption, BMRQ_musicseek, BMRQ_sensorimotor)
output = corr.test(variables)

corr_matrix = output$r
p_matrix <- output$p

colnames(corr_matrix) <- c('M@H-R General Score', 'Caregiver Beliefs', 'Caregiver Singingg', 'Attitude to Childhood Music', 'Home Music Associations', 'Music-Making Tendencies','Total BMRQ', 'Mood Regulation', 'Emotion Evocation', 'Social Reward', 'Absorption', 'Music Seeking',
                           'Sensorimotor')
rownames(corr_matrix) <- c('M@H-R General Score', 'Caregiver Beliefs', 'Caregiver Singingg', 'Attitude to Childhood Music', 'Home Music Associations', 'Music-Making Tendencies','Total BMRQ', 'Mood Regulation', 'Emotion Evocation', 'Social Reward', 'Absorption', 'Music Seeking',
                           'Sensorimotor')

pdf(file = "../figures/pleasing:displeasing_followup/BMRQ_corrplot_totals.pdf")

corrplot(corr_matrix, p.mat = p_matrix, insig = "label_sig",
         sig.level = c(0.001,0.01,0.05), pch.cex=0.9, pch.col = "black", tl.col = "black", type="lower",tl.srt =45, 
         col=colorRampPalette(c("darkblue","white","red"))(100),cl.lim=c(0,1))

dev.off()

#M@HR + ELA measures
variables = dplyr::select(full, 
                          g, F1, F2, F3, F4, F5, QUIC_sum, 
                          CHAOS_sum, deprivation_sum, Threat_sum)
output = corr.test(variables)

corr_matrix = output$r
p_matrix <- output$p

colnames(corr_matrix) <- c('M@H-R General Score', 'Caregiver Beliefs', 'Caregiver Singingg', 'Attitude to Childhood Music', 'Home Music Associations', 'Music-Making Tendencies', "QUIC Sum", "CHAOS Sum", "Deprivation Sum", "Threat Sum")
rownames(corr_matrix) <- c('M@H-R General Score', 'Caregiver Beliefs', 'Caregiver Singingg', 'Attitude to Childhood Music', 'Home Music Associations', 'Music-Making Tendencies', "QUIC Sum", "CHAOS Sum", "Deprivation Sum", "Threat Sum")

pdf(file = "../figures/pleasing:displeasing_followup/BMRQ_corrplot_totals.pdf")

corrplot(corr_matrix, p.mat = p_matrix, insig = "label_sig",
         sig.level = c(0.001,0.01,0.05), pch.cex=0.9, pch.col = "black", tl.col = "black", type="lower",tl.srt =45, 
         col=colorRampPalette(c("darkblue","white","red"))(100),cl.lim=c(0,1))

dev.off()
```