---
title: "2_cleaning"
author: "Nick Kathios"
date: '2023-01-16'
output: html_document
---
#load packages
```{r}
library(tidyverse)
```

#read in data
```{r}
scored_data <- read.csv(file="../../data/pleasing-displeasing_followup/scored_data.csv")
master <- read.csv(file="../../data/pleasing-displeasing_followup/pleasing_displeasing_scored.csv")
```

#clean data
```{r}
#removing Ps without ELA + HUMs
scored_data <- scored_data[complete.cases(scored_data[ , 391:422]),]
#removing Ps without STAI + CD.RISC
scored_data <- scored_data[complete.cases(scored_data[ , 431:432]),]
```

#merge dataframes
```{r}
names(scored_data)[20] <- "ID"
master <- master[-1]
names(master)[1] <- "ID"
'%notin%' <- Negate('%in%')
all_scored <- merge(master, scored_data, by="ID")


check <- subset(scored_data, scored_data$ID %notin%  all_scored$ID)

write.csv(all_scored, "../../data/pleasing-displeasing_followup/music_usage/all_scored.csv")
```

#demographics
```{r}
mean(all_scored$What.is.your.age.)
sd(all_scored$What.is.your.age.)
range(all_scored$What.is.your.age.)

table(all_scored$What.sex.were.you.assigned.at.birth.)
```

