---
title: "3_analysis"
author: "Nick Kathios"
date: '2023-01-16'
output: html_document
---

#load packages
```{r}
library(tidyverse)
library(lmerTest)
library(MuMIn)
library(AICcmodavg)
library(sjPlot)
library(corrplot)
library(psych)
library(ggrepel)
```

#read in data
```{r}
all_scored <- read.csv(file="../../data/pleasing-displeasing_followup/music_usage/all_scored.csv")
```

#HUMS, eBMRQ, Mental Health corr matrix
```{r}
cor.test(all_scored$CD.RISC_total, all_scored$deprivation_sum)

#HUMS, eBMRQ, Mental Health
variables = dplyr::select(all_scored, 
                          HUMS_adolescence_unhealthy, HUMS_adult_unhealthy,
                          HUMS_adolescence_healthy, HUMS_adult_healthy,
                          BMRQ_total, BMRQ_moodreg, BMRQ_emotion, BMRQ_socialreward,
                          BMRQ_absorption, BMRQ_musicseek, BMRQ_sensorimotor,PASS_total,
                          STAI_total, CD.RISC_total)
output = corr.test(variables)

corr_matrix = output$r
p_matrix <- output$p

colnames(corr_matrix) <- c('Unhealthy Adolescent Music Usage', 'Unhealthy Adult Music Usage','Healthy Adolescent Music Usage','Healthy Adult Music Usage', 'Total BMRQ', 'Mood Regulation', 'Emotion Evocation', 'Social Reward', 'Absorption', 'Music Seeking',
                           'Sensorimotor',"PAS", "STAI", "CDRISC")
rownames(corr_matrix) <- c('Unhealthy Adolescent Music Usage', 'Unhealthy Adult Music Usage','Healthy Adolescent Music Usage','Healthy Adult Music Usage', 'Total BMRQ', 'Mood Regulation', 'Emotion Evocation', 'Social Reward', 'Absorption', 'Music Seeking',
                           'Sensorimotor', "PAS", "STAI", "CDRISC")

pdf(file = "../../figures/pleasing:displeasing_followup/full_sample/eBMRQ_HUMS_mentalhealth.pdf")

corrplot(corr_matrix, p.mat = p_matrix, insig = "label_sig",
         sig.level = c(0.001,0.01,0.05), pch.cex=0.9, pch.col = "black", tl.col = "black", type="lower",tl.srt =45, diag=FALSE,
         col=colorRampPalette(c("darkblue","white","red"))(100),cl.lim=c(0,1))

dev.off()


CHAOS_ebmrqabs<-
  ggplot(data=all_scored, aes(x=CHAOS_sum, y=BMRQ_absorption)) +
         geom_point() +
  geom_smooth(method="lm") +
  theme_classic() +
  xlab("Total CHAOS Score") +
  ylab("eBMRQ Absorption Score") +
  theme( 
    axis.text.x = element_text(size=18),
    axis.text.y = element_text(size=18),
    axis.title.x = element_text(size=24),
    axis.title.y = element_text(size=24)
  )

cor.test(all_scored$CHAOS_sum, all_scored$BMRQ_absorption)

ggsave(file='../../figures/AIMS_paper/CHAOS_ebmrqabs.png',CHAOS_ebmrqabs)

Threat_ebmrqabs<-
  ggplot(data=all_scored, aes(x=Threat_sum, y=BMRQ_absorption)) +
         geom_point() +
  geom_smooth(method="lm") +
  theme_classic() +
  xlab("Total Threat Score") +
  ylab("eBMRQ Absorption Score") +
  theme( 
    axis.text.x = element_text(size=18),
    axis.text.y = element_text(size=18),
    axis.title.x = element_text(size=24),
    axis.title.y = element_text(size=24)
  )

cor.test(all_scored$Threat_sum, all_scored$BMRQ_absorption)

ggsave(file='../../figures/AIMS_paper/Threat_ebmrqabs.png',Threat_ebmrqabs)
```

#HUMS ~ eBMRQ
```{r}
m1 <- lm(scale(HUMS_adult_unhealthy) ~ scale(BMRQ_socialreward) + scale(BMRQ_emotion) + scale(BMRQ_moodreg) + scale(BMRQ_sensorimotor) + scale(BMRQ_musicseek) + scale(BMRQ_absorption), data=all_scored)
summary(m1)

m1 <- lm(scale(HUMS_adult_healthy) ~ scale(BMRQ_socialreward) + scale(BMRQ_emotion) + scale(BMRQ_moodreg) + scale(BMRQ_sensorimotor) + scale(BMRQ_musicseek) + scale(BMRQ_absorption) + scale(PASS_total) + scale(STAI_total), data=all_scored)
summary(m1)
summary <- summary(m1)
summary <- as.data.frame(summary[["coefficients"]])
p <- summary$`Pr(>|t|)`
p.adjust(p, method = "fdr", n = length(p))
#plot

eBMRQ_HUMS_coef <- 
plot_model(m1, show.values = TRUE,vline.color = "lightgrey") + 
  ylim(-.6, .6) +
  ggtitle("Healthy Music Usage Scores") +
  ylab("Standardized Beta Coefficient Estimates")+
  theme_light() +
  theme(title=element_text(family="Arial", size=20),
    axis.title.x = element_text(family="Arial", size=18),
    axis.title.y = element_text(family="Arial",size=18),
    axis.text.x = element_text(family="Arial", size=16),
    axis.text.y = element_text(family="Arial",size=16),
  ) +
  scale_x_discrete(labels=c("STAI", "PAS", "Absorption", "Music Seeking","Sensorimotor","Mood Regulation", "Emotion Evocation", "Social Reward"))

ggsave(plot=eBMRQ_HUMS_coef, '../../figures/pleasing:displeasing_followup/full_sample/eBMRQ_HUMS_coef.png',width=10)
```

#corrplots
```{r}
#eBMRQ + ELA Sum
variables = dplyr::select(all_scored, 
                          BMRQ_total, BMRQ_moodreg, BMRQ_emotion, BMRQ_socialreward, 
                          BMRQ_musicseek, 
                          BMRQ_sensorimotor,BMRQ_absorption,QUIC_sum, CHAOS_sum, 
                          deprivation_sum, Threat_sum, QUIC_child_total, CHAOS_child_total, 
                          deprivation_child_total, threat_childhood_total, 
                          QUIC_Adolescence_total, 
                          CHAOS_Adolescence_total, deprivation_Adolescence_total, threat_adolescence_total)
output = corr.test(variables)

corr_matrix = output$r
p_matrix <- output$p

colnames(corr_matrix) <- c('Total BMRQ', 'BMRQ - Mood Regulation', 
                           'BMRQ - Emotion Evocation', 'BMRQ -  Social Reward', 
                           'BMRQ - Music Seeking','BMRQ - Sensorimotor Reward', 
                           "BMRQ - Absorption", "QUIC Sum", "CHAOS Sum", 
                           "Deprivation Sum","Threat Sum","QUIC Childhood", "CHAOS Childhood", 
                           "Deprivation Childhood","Threat Childhood","QUIC Adolescence", "CHAOS Adolescence", 
                           "Deprivation Adolescence","Threat Adolescence")
rownames(corr_matrix) <- c('Total BMRQ', 'BMRQ - Mood Regulation', 
                           'BMRQ - Emotion Evocation', 'BMRQ -  Social Reward', 
                           'BMRQ - Music Seeking','BMRQ - Sensorimotor Reward', 
                           "BMRQ - Absorption", "QUIC Sum", "CHAOS Sum", 
                           "Deprivation Sum","Threat Sum","QUIC Childhood", "CHAOS Childhood", 
                           "Deprivation Childhood","Threat Childhood","QUIC Adolescence", "CHAOS Adolescence", 
                           "Deprivation Adolescence","Threat Adolescence")

pdf(file = "../../figures/pleasing:displeasing_followup/BMRQELAsum_study1.pdf")

corrplot(corr_matrix, p.mat = p_matrix, insig = "label_sig",
         sig.level = c(0.001,0.01,0.05), pch.cex=0.9, pch.col = "black", tl.col = "black", type="lower",tl.srt =45, diag=FALSE,
         col=colorRampPalette(c("darkblue","white","red"))(100),cl.lim=c(0,1))

dev.off()

#childhood
variables = dplyr::select(all_scored, 
                          BMRQ_total, BMRQ_moodreg, BMRQ_emotion, BMRQ_socialreward,
                          BMRQ_absorption, BMRQ_musicseek, BMRQ_sensorimotor, QUIC_child_total, 
                          CHAOS_child_total, deprivation_child_total, threat_childhood_total)
output = corr.test(variables)

corr_matrix = output$r
p_matrix <- output$p

colnames(corr_matrix) <- c('Total BMRQ', 'Mood Regulation', 'Emotion Evocation', 'Social Reward', 'Absorption', 'Music Seeking',
                           'Sensorimotor', "QUIC Childhood", "CHAOS Childhood", "Deprivation Childhood", "Threat Childhood")
rownames(corr_matrix) <- c('Total BMRQ', 'Mood Regulation', 'Emotion Evocation', 'Social Reward', 'Absorption', 'Music Seeking',
                           'Sensorimotor', "QUIC Childhood", "CHAOS Childhood", "Deprivation Childhood", "Threat Childhood")
pdf(file = "../../figures/pleasing:displeasing_followup/BMRQ_corrplot_childhood.pdf")

corrplot(corr_matrix, p.mat = p_matrix, insig = "label_sig",
         sig.level = c(0.001,0.01,0.05), pch.cex=0.9, pch.col = "black", tl.col = "black", type="lower",tl.srt =45, 
         col=colorRampPalette(c("darkblue","white","red"))(100),cl.lim=c(0,1))

dev.off()


#adolescence
variables = dplyr::select(all_scored, 
                          BMRQ_total, BMRQ_moodreg, BMRQ_emotion, BMRQ_socialreward,
                          BMRQ_absorption, BMRQ_musicseek, BMRQ_sensorimotor, QUIC_Adolescence_total, 
                          CHAOS_Adolescence_total, deprivation_Adolescence_total, threat_adolescence_total)
output = corr.test(variables)

corr_matrix = output$r
p_matrix <- output$p

colnames(corr_matrix) <- c('Total BMRQ', 'Mood Regulation', 'Emotion Evocation', 'Social Reward', 'Absorption', 'Music Seeking',
                           'Sensorimotor', "QUIC Adolescence", "CHAOS Adolescence", "Deprivation Adolescence", "Threat Adolescence")
rownames(corr_matrix) <- c('Total BMRQ', 'Mood Regulation', 'Emotion Evocation', 'Social Reward', 'Absorption', 'Music Seeking',
                           'Sensorimotor', "QUIC Adolescence", "CHAOS Adolescence", "Deprivation Adolescence", "Threat Adolescence")

pdf(file = "../../figures/pleasing:displeasing_followup/BMRQ_corrplot_adolescence.pdf")

corrplot(corr_matrix, p.mat = p_matrix, insig = "label_sig",
         sig.level = c(0.001,0.01,0.05), pch.cex=0.9, pch.col = "black", tl.col = "black", type="lower",tl.srt =45, 
         col=colorRampPalette(c("darkblue","white","red"))(100),cl.lim=c(0,1))

dev.off()
```

#is absorption related to ELA above and beyond other measures?
```{r}
m1 <-  lm(BMRQ_absorption ~ PASS_total + STAI_total, data=all_scored)
summary(m1)
m1 <- lm(CHAOS_sum ~ BMRQ_socialreward + BMRQ_emotion + BMRQ_moodreg + BMRQ_sensorimotor + BMRQ_musicseek + BMRQ_absorption , data=all_scored)
summary(m1)
summary <- summary(m1)
summary <- as.data.frame(summary[["coefficients"]])
p <- summary$`Pr(>|t|)`
p.adjust(p, method = "fdr", n = length(p))

m1 <- lm(QUIC_sum ~ BMRQ_socialreward + BMRQ_emotion + BMRQ_moodreg + BMRQ_sensorimotor + BMRQ_musicseek + BMRQ_absorption + PASS_total + STAI_total, data=all_scored)

summary(m1)
summary <- summary(m1)
summary <- as.data.frame(summary[["coefficients"]])
p <- summary$`Pr(>|t|)`
p.adjust(p, method = "fdr", n = length(p))

m1 <- lm(deprivation_sum ~ BMRQ_socialreward + BMRQ_emotion + BMRQ_moodreg + BMRQ_sensorimotor + BMRQ_musicseek + BMRQ_absorption + PASS_total + STAI_total, data=all_scored)
summary(m1)
summary <- summary(m1)
summary <- as.data.frame(summary[["coefficients"]])
p <- summary$`Pr(>|t|)`
p.adjust(p, method = "fdr", n = length(p))

m1 <- lm(Threat_sum ~ BMRQ_socialreward + BMRQ_emotion + BMRQ_moodreg + BMRQ_sensorimotor + BMRQ_musicseek + BMRQ_absorption, data=all_scored)
summary(m1)

#is there evidence that absorption is adaptive?
cor.test(all_scored$BMRQ_absorption, all_scored$CD.RISC_total)
cor.test(all_scored$BMRQ_absorption, all_scored$HUMS_adult_healthy)
cor.test(all_scored$BMRQ_absorption, all_scored$HUMS_adult_unhealthy)
```

#is any dimension of ELA related to music reward sensitivity? or healthy / unhealthy music usage?
```{r}
m1 <- lm(BMRQ_absorption ~ CHAOS_sum + QUIC_sum + deprivation_sum + Threat_sum + PASS_total + STAI_total, data=all_scored)
summary(m1)

m2 <- lm(HUMS_adult_healthy ~ CHAOS_sum + QUIC_sum + deprivation_sum + Threat_sum + PASS_total + STAI_total, data=all_scored)
summary(m2)

m3 <- lm(HUMS_adult_unhealthy ~  CHAOS_sum + STAI_total + PASS_total , data=all_scored)
summary(m3)
summary <- summary(m3)
summary <- as.data.frame(summary[["coefficients"]])
p <- summary$`Pr(>|t|)`
p.adjust(p, method = "fdr", n = length(p))
```

#is one dimenions of ELA associated w/ abs?
```{r}
m1 <- lm(BMRQ_absorption ~ CHAOS_sum + QUIC_sum + deprivation_sum + Threat_sum + PASS_total + STAI_total, data=all_scored)
summary(m1)
```

#moderation?
```{r}
m1 <- lm(scale(CD.RISC_total) ~ scale(deprivation_sum)*scale(BMRQ_absorption), data=all_scored)
summary(m1)
```


#absorption ~ HUMS + ~ Resilience
```{r}
all_scored$HUMS_adult_healthy
abs_unhealthyusage <-
  ggplot(data=all_scored, aes(x=BMRQ_absorption, y=HUMS_adult_unhealthy)) +
  geom_jitter(width = 0.065,height=0.065, alpha=0.5, color="#E69F00") +
  theme_classic() +
  geom_smooth(method="lm", color="#E69F00", fill="#E69F00") +
  xlab("BMRQ Absorption Score") +
  ylab("Unhealthy Music Usage Score")+
  theme( 
    axis.text.x = element_text(size=18),
    axis.text.y = element_text(size=18),
    axis.title.x = element_text(size=24),
    axis.title.y = element_text(size=24)
  )

ggsave(abs_unhealthyusage, file='../../figures/pleasing:displeasing_followup/abs_unhealthyusage.png')
  

HUMS_Absorption <- all_scored %>%
  dplyr::select(BMRQ_absorption, HUMS_adult_healthy, HUMS_adult_unhealthy) %>%
  pivot_longer(HUMS_adult_healthy:HUMS_adult_unhealthy, names_to = "type", values_to = "HUMS")

HUMS_Absorption$type <- ifelse(HUMS_Absorption$type=="HUMS_adult_unhealthy", "Unhealthy", "Healthy")

label <- expand.grid(
  HUMS=30,
  BMRQ_absorption = 15,
  type=c("Healthy", "Unhealthy")
)

label$HUMS <- ifelse(label$type=="Unhealthy", label$HUMS -1, label$HUMS )

abs_HUMS_label <- 
  ggplot(data=HUMS_Absorption, aes(x=BMRQ_absorption, y=HUMS)) +
  scale_color_manual(values=c("#E69F00","#56B4E9")) +
  scale_fill_manual(values=c("#E69F00","#56B4E9")) +
  geom_label_repel(aes(label = type, color=type),
   #              nudge_x = -0.8,
    #               na.rm = TRUE,
                  data=label,
                   family="Arial",
                 size=6,
                 min.segment.length = Inf) +
    theme_classic()

ggsave(abs_HUMS_label, file='../../figures/pleasing:displeasing_followup/abs_HUMS_label.png')

cor.test(all_scored$BMRQ_absorption, all_scored$CD.RISC_total)

HUMS_Absorption <- all_scored %>%
  dplyr::select(BMRQ_absorption, HUMS_adult_healthy, HUMS_adult_unhealthy, ID)

HUMS_Absorption$HUMS_adult_healthy <- scale(HUMS_Absorption$HUMS_adult_healthy)
HUMS_Absorption$HUMS_adult_unhealthy <- scale(HUMS_Absorption$HUMS_adult_unhealthy)



HUMS_Absorption <- HUMS_Absorption %>%
  pivot_longer(HUMS_adult_healthy:HUMS_adult_unhealthy, names_to = "type", values_to = "HUMS")

HUMS_Absorption$type <- ifelse(HUMS_Absorption$type=="HUMS_adult_unhealthy", "Unhealthy", "Healthy")
HUMS_Absorption$type <- as.factor(HUMS_Absorption$type)
HUMS_Absorption$absorption_scaled <- scale(HUMS_Absorption$BMRQ_absorption)

contrasts(HUMS_Absorption$type) <- c(-0.5,0.5)
m3 <- lmer((HUMS) ~ absorption_scaled*type + (1|ID), data=HUMS_Absorption)
summary(m3)

#plotting
##plotting
newdata <- expand.grid(
  absorption_scaled=seq(-2.092594,1.517042,0.01),
  HUMS = seq(-3.4162226, 4.0308494, 0.1),
  type = c("Healthy", "Unhealthy")
)

predictions<- predictSE(m3, newdata, se.fit = TRUE, print.matrix =
        TRUE, level = 0)

pred <- cbind(newdata, predictions)

pred$BMRQ_absorption <- (pred$absorption_scaled * attr(HUMS_Absorption$absorption_scaled, 'scaled:scale') + attr(HUMS_Absorption$absorption_scaled, 'scaled:center'))

HUMS_AIMS_plot<-
  ggplot(data=pred, aes(x=BMRQ_absorption, y=fit)) +
  geom_jitter(data=HUMS_Absorption, (aes(y=HUMS, color=type)),alpha=0.5,width = 0.09)+
  geom_line(aes(col=type))+
  geom_ribbon(aes(ymin=fit-se.fit, ymax=fit+se.fit, fill=type),alpha=0.25) +
  ylab('Music Usage Score \n(within subscale Z-score)') +
  xlab('eBMRQ Absorption Score') +
  theme_classic() +
 theme(
   legend.position = "none",
    axis.title.x = element_text(family="Arial", size=22),
    axis.title.y = element_text(family="Arial",size=22),
    axis.text.x = element_text(family="Arial", size=20),
    axis.text.y = element_text(family="Arial",size=20),
    strip.text.x = element_text(family="Arial",size=20)
  ) +
   scale_color_manual(values=c("#E69F00","#56B4E9")) +
  scale_fill_manual(values=c("#E69F00","#56B4E9"))


ggsave('../../figures/AIMS_paper/HUMS_Absorptionplot.png', HUMS_AIMS_plot, dpi=350)

cor.test(all_scored$CD.RISC_total, scale(all_scored$BMRQ_absorption))
```

#plotting res + abs
```{r}
abs_resilience<-
  ggplot(data=all_scored, aes(x=BMRQ_absorption, y=CD.RISC_total)) +
         geom_jitter(width=0.05, alpha=0.75) +
  geom_smooth(method="lm") +
  theme_classic() +
  xlab("eBMRQ Absorption Score") +
  ylab("CD.RISC-10 Score") +
  theme( 
    axis.text.x = element_text(size=18),
    axis.text.y = element_text(size=18),
    axis.title.x = element_text(size=24),
    axis.title.y = element_text(size=24)
  )

cor.test(all_scored$BMRQ_absorption, all_scored$CD.RISC_total)

ggsave(file='../../figures/AIMS_paper/abs_resilience.png',abs_resilience)
```

